- src/blaze/elm/compiler.clj
- src/blaze/elm/compiler/retrieve.clj
- test/blaze/elm/compiler/retrieve_test.clj
- test/blaze/elm/compiler_test.clj
> Change Direct Retrieval Through Datomic Entity into Index Access

- project.clj
- resources/org/hl7/elm_modelinfo/r1/jaxb.properties
> Cleanup Dependencies

- src/blaze/handler/fhir/transaction.clj
- test/blaze/handler/fhir/transaction_test.clj
> Fix 500 on Missing request Key in Transaction Bundles

- .clj-kondo/config.edn
- .gitignore
- .travis.yml
- Makefile
- deps.edn
- modules/cql/deps.edn
- modules/cql/src/blaze/elm/deps_infer.clj
- modules/cql/src/blaze/elm/equiv_relationships.clj
- modules/cql/src/blaze/elm/normalizer.clj
- modules/cql/src/blaze/elm/spec.clj
- modules/cql/src/blaze/elm/type_infer.clj
- modules/datomic/src/blaze/datomic.clj
- modules/extern-terminology-service/src/blaze/terminology_service/extern.clj
- modules/interaction/src/blaze/interaction/spec.clj
- modules/interaction/test/blaze/interaction/history/test_util.clj
- modules/interaction/test/blaze/interaction/history/util_test.clj
- modules/interaction/test/blaze/interaction/update_test.clj
- modules/module-base/src/blaze/module.clj
- modules/openid-auth/src/blaze/openid_auth.clj
- modules/openid-auth/test/blaze/openid_auth_test.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/handler/impl_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/rest-api/src/blaze/rest_api.clj
- modules/rest-api/test/blaze/rest_api_test.clj
- modules/rest-util/test/blaze/bundle_test.clj
- modules/thread-pool-executor-collector/src/blaze/thread_pool_executor_collector.clj
- src/blaze/core.clj
- src/blaze/system.clj
> Add Linting with clj-kondo

- evaluate-measure.sh
- modules/cql/src/blaze/cql_translator.clj
- modules/cql/test/blaze/cql_translator_test.clj
- modules/datomic-test-util/src/blaze/datomic/test_util.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/handler/impl.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/spec.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/handler/impl_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q19-stratifier-ageclass-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q19-stratifier-ageclass-query.cql
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q20-stratifier-city-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q20-stratifier-city-query.cql
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q21-stratifier-city-of-only-women-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q21-stratifier-city-of-only-women-query.cql
> Stratifiers

- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q20-stratifier-city-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q21-stratifier-city-of-only-women-query.cql
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q22-stratifier-multiple-cities-fail-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q22-stratifier-multiple-cities-fail-query.cql
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q23-stratifier-ageclass-and-gender-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q23-stratifier-ageclass-and-gender-query.cql
> Implement Stratifier Components in Evaluate Measure

- src/blaze/system.clj
- test/blaze/system_test.clj
> Ignore Blank Environment Variables

- modules/datomic/src/blaze/datomic/quantity.clj
- modules/datomic/src/blaze/datomic/transaction.clj
- modules/datomic/src/blaze/datomic/value.clj
- modules/datomic/test/blaze/datomic/transaction_test.clj
- modules/datomic/test/blaze/datomic/value_test.clj
> Fix Zero Change Updates in Transaction

- Makefile
- README.md
- docker-compose.yml
- docs/index.adoc
- modules/cql/src/blaze/elm/compiler.clj
- modules/cql/src/blaze/elm/compiler/property.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q25-stratifier-collection-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q25-stratifier-collection-query.cql
- pom.xml
- src/blaze/system.clj
> Implement Runtime Choice Type Resolution in Property Expression

- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Allow Multiple Search Parameters for ID Search

- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/handler/impl.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/middleware/params.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/handler/impl_test.clj
> Allow $evaluate-measure on Measure Type

- modules/cql/src/blaze/elm/compiler.clj
- modules/cql/src/blaze/elm/compiler/function.clj
- modules/cql/src/blaze/elm/compiler/property.clj
- modules/cql/src/blaze/elm/nil.clj
- modules/cql/src/blaze/elm/protocols.clj
- modules/cql/src/blaze/elm/quantity.clj
- modules/cql/src/blaze/elm/spec.clj
- modules/cql/test/blaze/elm/compiler/property_test.clj
- modules/cql/test/blaze/elm/compiler_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q27-stratifier-calculated-bmi-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q27-stratifier-calculated-bmi-query.cql
> Implement ConvertQuantity

- .travis.yml
- modules/cql/src/blaze/elm/compiler.clj
- modules/cql/src/blaze/elm/compiler/property.clj
- modules/cql/src/blaze/elm/compiler/query.clj
- modules/cql/src/blaze/elm/spec.clj
- modules/cql/src/blaze/elm/type_infer.clj
- modules/cql/test/blaze/elm/compiler/property_test.clj
- modules/cql/test/blaze/elm/compiler_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q27-stratifier-calculated-bmi-data.json
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q27-stratifier-calculated-bmi-query.cql
> Implement Sort ByExpression

- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj
> Improve Memory Usage at Queries over Large Resource Amounts

- modules/db/src/blaze/db/impl/index.clj
- modules/db/src/blaze/db/indexer.clj
- modules/db/src/blaze/db/indexer/tx.clj
- modules/db/src/blaze/db/indexer_spec.clj
- modules/db/src/blaze/db/tx_log.clj
- modules/db/src/blaze/db/tx_log/local.clj
- modules/db/test/blaze/db/db_test.clj
- modules/db/test/blaze/db/impl/bytes_spec.clj
- modules/db/test/blaze/db/impl/bytes_test.clj
- modules/db/test/blaze/db/impl/index_spec.clj
- modules/db/test/blaze/db/indexer/tx_test.clj
- modules/interaction/test/blaze/interaction/history/instance_test.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
- modules/interaction/test/blaze/interaction/update_test.clj
> Make PUT's Idempotent

- modules/interaction/src/blaze/interaction/create.clj
- modules/interaction/src/blaze/interaction/delete.clj
- modules/interaction/src/blaze/interaction/history/instance.clj
- modules/interaction/src/blaze/interaction/history/system.clj
- modules/interaction/src/blaze/interaction/history/type.clj
- modules/interaction/src/blaze/interaction/read.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/src/blaze/interaction/transaction.clj
- modules/interaction/src/blaze/interaction/update.clj
#127 Log output implemented in the style of HTTP request commands.
> Log Resource Access in Debug Mode 

- Makefile
- README.md
- docker-compose.yml
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- pom.xml
- src/blaze/system.clj
> Improve Visibility of Measure Evaluation Duration

- README.md
- modules/db/src/blaze/db/indexer/resource.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure.clj
- resources/blaze.edn
> Make Number of Evaluate Measure Threads Configurable

- modules/fhir-path/src/blaze/fhir_path.clj
- modules/fhir-path/test/blaze/fhir_path_test.clj
> Fix FHIRPath not Returning Boolean False

- modules/db/src/blaze/db/api_spec.clj
- modules/interaction/.clj-kondo/config.edn
- modules/interaction/src/blaze/interaction/history/system.clj
- modules/interaction/src/blaze/interaction/history/type.clj
- modules/interaction/src/blaze/interaction/history/util.clj
- modules/interaction/src/blaze/interaction/history/util_spec.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/src/blaze/interaction/update.clj
- modules/interaction/test/blaze/interaction/history/instance_test.clj
- modules/interaction/test/blaze/interaction/history/system_test.clj
- modules/interaction/test/blaze/interaction/history/type_test.clj
- modules/interaction/test/blaze/interaction/history/util_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/src/blaze/handler/fhir/util_spec.clj
- modules/rest-util/src/blaze/handler/util_spec.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
> Add pagination support

- Makefile
- modules/db-protocols/deps.edn
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db-stub/src/blaze/db/api_stub.clj
- modules/db/NOTES.md
- modules/db/deps.edn
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/impl/codec.clj
- modules/db/src/blaze/db/impl/index.clj
- modules/db/src/blaze/db/impl/index/resource_as_of.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/list.clj
- modules/db/src/blaze/db/impl/search_param/special.clj
- modules/db/src/blaze/db/indexer/resource.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/codec_spec.clj
- modules/db/test/blaze/db/impl/codec_test.clj
- modules/db/test/blaze/db/impl/index/resource_test.clj
- modules/db/test/blaze/db/impl/index_spec.clj
- modules/db/test/blaze/db/impl/search_param_spec.clj
- modules/db/test/blaze/db/impl/search_param_test.clj
- modules/db/test/blaze/db/indexer/resource_test.clj
- modules/db/test/blaze/db/indexer/tx_test.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/rest-api/src/blaze/rest_api.clj
- modules/search-param-registry/deps.edn
- modules/search-param-registry/src/blaze/db/search_param_registry.clj
- modules/search-param-registry/src/blaze/db/search_param_registry/spec.clj
- resources/blaze.edn
> Implement Searching by List

- modules/interaction/src/blaze/interaction/history/instance.clj
- modules/interaction/src/blaze/interaction/history/system.clj
- modules/interaction/src/blaze/interaction/history/type.clj
- modules/interaction/src/blaze/interaction/history/util.clj
- modules/interaction/src/blaze/interaction/history/util_spec.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/history/util_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/src/blaze/handler/fhir/util_spec.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
> Fix Handling of HTTP Query Params

- .clj-kondo/config.edn
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/api_spec.clj
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/impl/db.clj
- modules/db/test/blaze/db/api_test.clj
- modules/interaction/src/blaze/interaction/transaction.clj
- modules/operations/measure-evaluate-measure/.clj-kondo/config.edn
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/handler/impl.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
- modules/operations/measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/spec.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_spec.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/handler/impl_test.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_spec.clj
- modules/operations/measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/rest-util/src/blaze/handler/util.clj
- modules/rest-util/src/blaze/middleware/fhir/metrics.clj
> Implement Evaluating Measures with Subject-Lists

- deps.edn
- modules/coll/deps.edn
- modules/cql/deps.edn
- modules/db/deps.edn
- modules/fhir-path/deps.edn
- modules/fhir-structure/deps.edn
- modules/interaction/deps.edn
- modules/openid-auth/deps.edn
- modules/operations/measure-evaluate-measure/deps.edn
- modules/rest-api/deps.edn
- modules/rest-util/deps.edn
- modules/rocksdb/deps.edn
- modules/search-param-registry/deps.edn
> Update test.check and kaocha

- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/impl/index.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/list.clj
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/index_spec.clj
- modules/db/test/blaze/db/impl/search_param_spec.clj
- modules/db/test/blaze/db/impl/search_param_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/search-param-registry/src/blaze/db/search_param_registry/spec.clj
> Implement Reference Search Identifier Modifier

- Makefile
- README.md
- docker-compose.yml
- modules/db/deps.edn
- modules/db/src/blaze/db/indexer/tx.clj
- modules/db/src/blaze/db/indexer_spec.clj
- modules/db/src/blaze/db/spec.clj
- modules/db/src/blaze/db/tx_log/local.clj
- modules/db/src/blaze/db/tx_log/local/references.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/indexer/tx_test.clj
- modules/db/test/blaze/db/tx_log/local/references_spec.clj
- modules/db/test/blaze/db/tx_log/local/references_test.clj
- modules/db/test/blaze/db/tx_log/local_spec.clj
- modules/fhir-structure/src/blaze/fhir/spec.clj
- modules/interaction/test/blaze/interaction/create_test.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
- modules/interaction/test/blaze/interaction/update_test.clj
- pom.xml
- src/blaze/system.clj
> Enforce Referential Integrity

- modules/rest-api/src/blaze/rest_api.clj
- modules/rest-api/test/blaze/rest_api_test.clj
Add Diagnostics Message into Operations Outcome on Method Not Allowed.
Add Test for verification.
> Add Diagnostics Message to Method Not Allowed Issues #184

- modules/interaction/src/blaze/interaction/read.clj
- modules/interaction/test/blaze/interaction/read_test.clj
Improve Operations Outcome on not found Ressource.
Add Diagnostics Message with FHRIR Path.
> Add Diagnostics Message to Object Not Found Issues #185

- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/handler/impl.clj
- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/middleware/params.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/handler/impl_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/middleware/params_test.clj
> Fix Failure on Missing periodStart Query Parameter

- modules/fhir-structure/src/blaze/fhir/spec.clj
- modules/fhir-structure/test/blaze/fhir/spec_test.clj
- modules/interaction/src/blaze/interaction/create.clj
- modules/interaction/src/blaze/interaction/transaction.clj
- modules/interaction/src/blaze/interaction/update.clj
- modules/interaction/test/blaze/interaction/create_test.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
- modules/interaction/test/blaze/interaction/update_test.clj
- modules/rest-util/src/blaze/handler/util.clj
Still work in progress.
TODO: 
- change from /fhir-spec/valid? to  modified /fhir-spec/explain-data in all useful situations. 
- maybe add more unit tests
What do you think so far?
> 166 invalid resources

- modules/db/src/blaze/db/node.clj
> Fix Hanging Transaction Tests

- modules/db/deps.edn
> Improve Code Coverage

- Makefile
- README.md
- docker-compose.yml
- modules/fhir-structure/src/blaze/fhir/spec/impl.clj
- modules/fhir-structure/test/blaze/fhir/spec_test.clj
- perf-test/gatling/pom.xml
- pom.xml
- src/blaze/system.clj
> Fix Validation of base64Binary Data

- Makefile
- README.md
- docker-compose.yml
- modules/cql/deps.edn
- modules/cql/resources/blaze/fhir-modelinfo-4.0.0.xml
- modules/cql/test/blaze/cql_translator_test.clj
- modules/db-tx-log-kafka/deps.edn
- modules/fhir-client/deps.edn
- modules/fhir-path/deps.edn
- modules/fhir-structure/deps.edn
- modules/openid-auth/deps.edn
- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
- modules/structure-definition/deps.edn
- perf-test/gatling/pom.xml
- pom.xml
- src/blaze/system.clj
> Fix Issue Parsing of Large CQL Queries Never Finishes

- Makefile
- README.md
- docker-compose.yml
- docs/performance.md
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/api_spec.clj
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/impl/codec.clj
- modules/db/src/blaze/db/impl/index.clj
- modules/db/src/blaze/db/impl/index/resource_handle.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/list.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/codec_spec.clj
- modules/db/test/blaze/db/impl/codec_test.clj
- modules/db/test/blaze/db/impl/index/resource_as_of_spec.clj
- modules/db/test/blaze/db/impl/index/resource_handle_spec.clj
- modules/db/test/blaze/db/impl/index/system_as_of_spec.clj
- modules/db/test/blaze/db/impl/index/type_as_of_spec.clj
- modules/db/test/blaze/db/impl/index_spec.clj
- modules/db/test/blaze/db/impl/search_param_spec.clj
- modules/db/test/blaze/db/impl/search_param_test.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- perf-test/gatling/pom.xml
- pom.xml
- src/blaze/system.clj
> Improve Performance of Paging of Search Type

- docs/performance.md
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/api_spec.clj
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/impl/db.clj
- modules/db/src/blaze/db/impl/index.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/list.clj
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/impl/index_spec.clj
- modules/interaction/src/blaze/interaction/history/type.clj
- modules/interaction/src/blaze/interaction/search/nav.clj
- modules/interaction/src/blaze/interaction/search/nav_spec.clj
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/interaction/src/blaze/interaction/search_compartment.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/search_compartment_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Improve Error Handling on Unknown Search Parameters

- modules/async/test/blaze/async/comp_test.clj
- modules/db-tx-log/src/blaze/db/tx_log.clj
- modules/db-tx-log/src/blaze/db/tx_log/spec.clj
- modules/db-tx-log/test/blaze/db/tx_log/spec_test.clj
- modules/db-tx-log/test/blaze/db/tx_log_test.clj
- modules/db/.clj-kondo/config.edn
- modules/db/deps.edn
- modules/db/src/blaze/db/impl/codec.clj
- modules/db/src/blaze/db/impl/index/resource_as_of.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/codec_spec.clj
- modules/db/test/blaze/db/impl/codec_test.clj
> Terminate Variable-Length Index Components

- Makefile
- README.md
- docker-compose.yml
- docs/performance.md
- modules/interaction/src/blaze/interaction/history/instance.clj
- modules/interaction/src/blaze/interaction/history/system.clj
- modules/interaction/src/blaze/interaction/history/type.clj
- modules/interaction/src/blaze/interaction/search_compartment.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/src/blaze/interaction/transaction.clj
- modules/interaction/test/blaze/interaction/history/instance_test.clj
- modules/interaction/test/blaze/interaction/history/system_test.clj
- modules/interaction/test/blaze/interaction/history/type_test.clj
- modules/interaction/test/blaze/interaction/search_compartment_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
- perf-test/gatling/pom.xml
- pom.xml
- src/blaze/system.clj
> Add Resource Id to all generated Bundles

- modules/cql/Makefile
- modules/cql/deps.edn
- modules/cql/src/blaze/elm/quantity.clj
- modules/cql/src/blaze/elm/spec.clj
- modules/cql/test/blaze/cql_test.clj
- modules/cql/test/blaze/elm/compiler_test.clj
- modules/cql/test/blaze/elm/fhir-ucum-units.tsv
- modules/cql/test/blaze/elm/quantity_spec.clj
- modules/cql/test/blaze/elm/quantity_test.clj
- modules/operation-measure-evaluate-measure/Makefile
> Fix Parsing of Units from Lab Domain

- modules/cql/src/blaze/cql_translator.clj
> Set Locale to English to Prevent a CQL Parsing Bug

- .github/workflows/build.yml
- codecov.yml
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/node_test.clj
> Coverage Reports wait for all Tests

- modules/fhir-client/src/blaze/fhir_client.clj
- modules/fhir-client/src/blaze/fhir_client/impl.clj
- modules/fhir-client/test/blaze/fhir_client_test.clj
- modules/interaction/src/blaze/interaction/history/system.clj
- modules/interaction/src/blaze/interaction/history/util.clj
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/interaction/src/blaze/interaction/search/util.clj
- modules/interaction/src/blaze/interaction/search_compartment.clj
- modules/interaction/src/blaze/interaction/search_system.clj
- modules/interaction/test/blaze/interaction/history/util_spec.clj
- modules/interaction/test/blaze/interaction/history/util_test.clj
- modules/interaction/test/blaze/interaction/search_system_spec.clj
- modules/interaction/test/blaze/interaction/search_system_test.clj
- modules/rest-api/src/blaze/rest_api.clj
- modules/rest-api/src/blaze/rest_api/spec.clj
- modules/rest-api/test/blaze/rest_api_test.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/src/blaze/handler/fhir/util_spec.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
- resources/blaze.edn
> Implement System Search Functionality

- modules/fhir-structure/src/blaze/fhir/spec.clj
- modules/fhir-structure/src/blaze/fhir/spec/impl.clj
- modules/fhir-structure/test/blaze/fhir/spec/impl_test.clj
- modules/fhir-structure/test/blaze/fhir/spec_test.clj
> Fix Error Reporting on Invalid Cardinality

- modules/rest-api/src/blaze/rest_api/middleware/resource.clj
- modules/rest-api/test/blaze/rest_api/middleware/resource_test.clj
> Return Error on Missing or Unknown Content-Type Header

- modules/fhir-structure/src/blaze/fhir/spec/type.clj
- modules/fhir-structure/test/blaze/fhir/spec/type_test.clj
- modules/rest-api/src/blaze/rest_api.clj
> Fix Broken Copyright property in Capability Statement

- modules/db/src/blaze/db/impl/search_param/list.clj
- modules/db/test/blaze/db/impl/search_param/composite_test.clj
- modules/db/test/blaze/db/impl/search_param/date_test.clj
- modules/db/test/blaze/db/impl/search_param/list_test.clj
- modules/db/test/blaze/db/impl/search_param/quantity_test.clj
- modules/db/test/blaze/db/impl/search_param/string_test.clj
- modules/db/test/blaze/db/impl/search_param/token_test.clj
> Fix missing Name of Search Param _list in CapabilityStatement

- modules/anomaly/src/blaze/anomaly.clj
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/composite.clj
- modules/db/src/blaze/db/impl/search_param/date.clj
- modules/db/src/blaze/db/impl/search_param/quantity.clj
- modules/db/src/blaze/db/impl/search_param/token.clj
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/search_param/composite_test.clj
- modules/db/test/blaze/db/impl/search_param/date_test.clj
- modules/db/test/blaze/db/impl/search_param/quantity_test.clj
- modules/db/test/blaze/db/impl/search_param_spec.clj
- modules/fhir-structure/src/blaze/fhir/spec/type.clj
- modules/fhir-structure/src/blaze/fhir/spec/type/system.clj
- modules/fhir-structure/src/blaze/fhir/spec/type/system_spec.clj
- modules/fhir-structure/test/blaze/fhir/spec/type/system_test.clj
- modules/fhir-structure/test/blaze/fhir/spec_test.clj
> Implement Composite Search Parameters with Token Second Component

- dev/blaze/dev.clj
- modules/db/src/blaze/db/impl/metrics.clj
- modules/db/test/blaze/db/impl/iterators_test.clj
- modules/db/test/blaze/db/impl/metrics_test.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/metrics.clj
- resources/blaze.edn
- src/blaze/metrics.clj
> Use a Separate Statistics Object per RocksDB Instance

- modules/fhir-path/src/blaze/fhir_path.clj
- modules/fhir-path/test/blaze/fhir_path_test.clj
> Fix FHIRPath Evaluation Error

- modules/cql/src/blaze/elm/list.clj
- modules/cql/test/blaze/elm/compiler_test.clj
- modules/cql/test/blaze/elm/list_test.clj
> Fix Intersect on Queries

- Makefile
- README.md
- docker-compose.yml
- docs/cql-queries.md
- docs/deployment/docker-deployment.md
- docs/deployment/manual-deployment.md
- modules/fhir-structure/src/blaze/fhir/spec/impl.clj
- modules/rest-api/src/blaze/rest_api.clj
- perf-test/gatling/pom.xml
- pom.xml
- src/blaze/system.clj
> Fix Memory Leak on Validation

- Makefile
- README.md
- docker-compose.yml
- docs/cql-queries.md
- docs/deployment/docker-deployment.md
- docs/deployment/manual-deployment.md
- modules/db/deps.edn
- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/resource_cache.clj
- modules/db/src/blaze/db/resource_handle_cache.clj
- modules/db/src/blaze/db/spec.clj
- modules/db/test/blaze/db/node/transaction_test.clj
- modules/db/test/blaze/db/node/validation_test.clj
- modules/db/test/blaze/db/resource_cache_spec.clj
- modules/db/test/blaze/db/resource_cache_test.clj
- modules/db/test/blaze/db/resource_handle_cache_test.clj
- modules/db/test/blaze/db/tx_log/local_test.clj
- modules/interaction/src/blaze/interaction/transaction.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
- modules/rest-util/deps.edn
- modules/rest-util/src/blaze/bundle_spec.clj
- modules/rest-util/src/blaze/handler/util.clj
- modules/rest-util/test/blaze/handler/util_test.clj
- perf-test/gatling/pom.xml
- pom.xml
- src/blaze/system.clj
> Fix Processing of Empty Transaction Bundles

- modules/db/src/blaze/db/api_spec.clj
- modules/db/src/blaze/db/impl/codec.clj
- modules/fhir-structure/src/blaze/fhir/spec/spec.clj
- modules/interaction/deps.edn
- modules/interaction/src/blaze/interaction/create_spec.clj
- modules/interaction/src/blaze/interaction/delete_spec.clj
- modules/interaction/src/blaze/interaction/history/instance_spec.clj
- modules/interaction/src/blaze/interaction/history/system_spec.clj
- modules/interaction/src/blaze/interaction/history/type_spec.clj
- modules/interaction/src/blaze/interaction/read_spec.clj
- modules/interaction/src/blaze/interaction/search_compartment_spec.clj
- modules/interaction/src/blaze/interaction/search_system_spec.clj
- modules/interaction/src/blaze/interaction/search_type_spec.clj
- modules/interaction/src/blaze/interaction/transaction_spec.clj
- modules/interaction/src/blaze/interaction/update_spec.clj
- modules/rest-util/deps.edn
- modules/rest-util/test/blaze/bundle_test.clj
- modules/rest-util/test/blaze/middleware/fhir/metrics_test.clj
- modules/spec/src/blaze/spec.clj
- profiling/blaze/profiling.clj
The Ring handlers we use return CompletableFutures, which isn't allowed
by Ring Spec.
> Remove Ring-Spec

- README.md
- docs/conformance.md
- docs/conformance/cql.md
I took it from the old Asciidoc.
> Add CQL Conformance

- .github/workflows/build.yml
- modules/cql/.clj-kondo/config.edn
- modules/db/.clj-kondo/config.edn
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Make Lists of Values of OR Search Parameters Unique

- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/search_param_spec.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Fix Inconsistent Paged Results on Disjunctive FHIR Searches

- .github/workflows/build.yml
- docs/deployment/environment-variables.md
- docs/implementation/database.md
- modules/byte-string/src/blaze/byte_string.clj
- modules/byte-string/src/blaze/byte_string_spec.clj
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/impl/codec.clj
- modules/db/src/blaze/db/impl/index/resource_search_param_value.clj
- modules/db/src/blaze/db/impl/index/search_param_value_resource.clj
- modules/db/src/blaze/db/impl/iterators.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/composite.clj
- modules/db/src/blaze/db/impl/search_param/date.clj
- modules/db/src/blaze/db/impl/search_param/quantity.clj
- modules/db/src/blaze/db/impl/search_param/string.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/codec_spec.clj
- modules/db/test/blaze/db/impl/codec_test.clj
- modules/db/test/blaze/db/impl/index/resource_search_param_value_spec.clj
- modules/db/test/blaze/db/impl/index/search_param_value_resource_spec.clj
- modules/db/test/blaze/db/impl/iterators_spec.clj
- modules/db/test/blaze/db/impl/search_param/date_test.clj
- modules/db/test/blaze/db/impl/search_param/quantity/spec.clj
- modules/db/test/blaze/db/impl/search_param_test.clj
- modules/db/test/blaze/db/node/resource_indexer_test.clj
- resources/blaze.edn
> Fix FHIR Date Search

- .github/workflows/build.yml
See: https://github.com/synthetichealth/synthea/pull/756
> Try to make Synthea Runs Deterministic

- .github/scripts/download-resources.sh
- .github/workflows/build.yml
- modules/byte-string/src/blaze/byte_string.clj
- modules/byte-string/src/blaze/byte_string_spec.clj
- modules/cql/src/blaze/elm/compiler/list_operators.clj
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/impl/db.clj
- modules/db/src/blaze/db/impl/search_param/util.clj
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/index/resource_search_param_value_spec.clj
- modules/interaction/src/blaze/interaction/search/include.clj
- modules/interaction/src/blaze/interaction/search/nav.clj
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/interaction/src/blaze/interaction/search/params/include.clj
- modules/interaction/src/blaze/interaction/search/util.clj
- modules/interaction/src/blaze/interaction/search_compartment.clj
- modules/interaction/src/blaze/interaction/search_system.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/search/include_spec.clj
- modules/interaction/test/blaze/interaction/search/include_test.clj
- modules/interaction/test/blaze/interaction/search/nav_test.clj
- modules/interaction/test/blaze/interaction/search/params/include_spec.clj
- modules/interaction/test/blaze/interaction/search/params/include_test.clj
- modules/interaction/test/blaze/interaction/search/spec.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Implement Search Param _include

- .github/workflows/build.yml
- modules/cql/deps.edn
- modules/cql/resources/blaze/fhir-modelinfo-4.0.0.xml
- modules/cql/src/blaze/cql_translator.clj
- modules/fhir-path/deps.edn
> Update cqframework to v1.5.2

- .github/workflows/build.yml
- modules/interaction/src/blaze/interaction/search/include.clj
- modules/interaction/src/blaze/interaction/search/nav.clj
- modules/interaction/src/blaze/interaction/search/params/include.clj
- modules/interaction/test/blaze/interaction/search/include_test.clj
- modules/interaction/test/blaze/interaction/search/nav_test.clj
- modules/interaction/test/blaze/interaction/search/params/include_test.clj
- modules/interaction/test/blaze/interaction/search/spec.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Allow Multiple Includes with same Type

- modules/db-resource-store/src/blaze/db/resource_store/kv.clj
- modules/db-resource-store/test/blaze/db/resource_store/kv_test.clj
- modules/db-stub/src/blaze/db/api_stub.clj
- modules/db/test-perf/blaze/db/api_test_perf.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
- modules/db/test/blaze/db/node_test.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
- resources/blaze.edn
> Use a Separate Thread Pool for Reading Resources

- modules/db/src/blaze/db/node/tx_indexer/verify.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
> Fix Total Counter on Recreating a Resource

- modules/db-resource-store-cassandra/src/blaze/db/resource_store/cassandra.clj
- modules/db-resource-store-cassandra/test/blaze/db/resource_store/cassandra_test.clj
Convert exceptions to anomalies and especially the DriverTimeoutException into an anomaly with category busy.
> Improve Cassandra Error Reporting

- modules/db-resource-store-cassandra/src/blaze/db/resource_store/cassandra.clj
- modules/db-resource-store-cassandra/test/blaze/db/resource_store/cassandra_test.clj
Covert exceptions to anomalies and especially the DriverTimeoutException and WriteTimeoutException into an anomaly with category busy.
> Improve Cassandra Error Reporting While Writing

- modules/interaction/src/blaze/interaction/search/include.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/search/include_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
The FHIR Spec requires, that includes don't count to the page size. Before I discovered this, I tried to overshoot the number of resources per page as little as possible.
> Fix Paging with Includes

- Dockerfile
> Migrate to a Java 15 Runtime

- docs/implementation/database.md
- modules/anomaly/src/blaze/anomaly.clj
- modules/db/src/blaze/db/impl/codec.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/composite.clj
- modules/db/src/blaze/db/impl/search_param/number.clj
- modules/db/src/blaze/db/impl/search_param/quantity.clj
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/search_param/composite_test.clj
- modules/db/test/blaze/db/impl/search_param/number_test.clj
- modules/db/test/blaze/db/impl/search_param/quantity_test.clj
> Implement Search Parameters of Type Number

- modules/db/src/blaze/db/impl/search_param/date.clj
- modules/db/test/blaze/db/api_test.clj
> Use Implementation of ge/le for gt/lt in Date Search Params

- .github/scripts/search-observation-profile.sh
- .github/workflows/build.yml
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Support _profile Search Parameter

- modules/anomaly/src/blaze/anomaly.clj
- modules/fhir-structure/src/blaze/fhir/spec/spec.clj
- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/handler/impl_test.clj
> Add Measure Evaluation Duration to MeasureReport

- modules/db/test/blaze/db/api_test.clj
The test was failing in CI. That's because it's not guaranteed that
parallel calls to `d/transact` will result in ordered return of db's
with increasing t's.
I rewrote the test using `d/as-of` for obtaining databases with all t's
since start. Since we create one patient in every transaction, the
number of patients has to be equal to the t of the database.
> Fix Parallel Transaction Creation Test

- .github/scripts/evaluate-measure.sh
- .github/workflows/build.yml
Each year this query will return fewer patients. So I removed it.
> Remove Time Dependent Query

- .github/workflows/build.yml
- dev/blaze/dev/db.clj
- modules/rest-api/src/blaze/rest_api.clj
- modules/rest-api/test/blaze/rest_api_test.clj
> Fix Failing OPTIONS Request

- modules/db/src/blaze/db/cache_collector.clj
- modules/db/test/blaze/db/cache_collector_test.clj
I created a single counter-metric-family function that takes a metric value getter function instead of hard coding all metic family functions.
Also use run! instead of doseq to add metric values.
> Refactor Cache Collector

- modules/async/src/blaze/async/flow.clj
- modules/async/test/blaze/async/flow_test.clj
- modules/db-stub/src/blaze/db/api_stub.clj
- modules/db/src/blaze/db/tx_log/local.clj
- modules/fhir-structure/src/blaze/fhir/spec/impl.clj
Also use run! instead of doseq.
> Refactor Doseq

- modules/db/test/blaze/db/node_test.clj
Because the GitHub Actions CI is quite slow, sometimes the lines 116 and 117 are not covered. Add another test that should cover that lines.
> Fix Test Coverage for Node

- .github/scripts/batch.sh
- .github/scripts/conditional-create.sh
- .github/scripts/delete.sh
- .github/scripts/download-resources-query.sh
- .github/scripts/download-resources.sh
- .github/scripts/evaluate-measure-subject-list.sh
- .github/scripts/evaluate-measure.sh
- .github/scripts/evaluate-patient-q1-measure.sh
- .github/scripts/revinclude.sh
- .github/scripts/search-compartment.sh
- .github/scripts/search-observation-profile.sh
- .github/scripts/search-patient-last-updated.sh
- .github/scripts/transaction-rw.sh
- .github/scripts/transaction.sh
Also introduced the FHIR base URL as Variable in some more scripts.
> Add Integration Test for Conditional Create

- modules/db/test/blaze/db/node_test.clj
On GitHub Actions, the VM is quite slow and has only two cores. So indexing errors are often caught directly rather than by the watch because the indexing takes place before the result getting and not in parallel. The slow resource store should to the trick here.
> Fix Flappy Code Coverage in Node

- docs/cql-queries/command-line.md
- evaluate-measure.sh
> Extend the CQL Evaluation Script Outputting a List of Patients

- modules/fhir-path/src/blaze/fhir_path.clj
- modules/fhir-path/test/blaze/fhir_path_test.clj
See: https://www.hl7.org/fhir/fhirpath.html#functions
> Implement FHIRPath Function extension

- modules/cql/src/blaze/elm/compiler/interval_operators.clj
- modules/cql/src/blaze/elm/compiler/reusing_logic.clj
- modules/cql/src/blaze/elm/compiler/type_operators.clj
- modules/cql/src/blaze/elm/decimal.clj
- modules/cql/src/blaze/elm/interval.clj
- modules/cql/src/blaze/elm/normalizer.clj
- modules/cql/src/blaze/elm/spec.clj
- modules/cql/test/blaze/elm/compiler/arithmetic_operators_test.clj
- modules/cql/test/blaze/elm/compiler/interval_operators_test.clj
- modules/cql/test/blaze/elm/compiler/reusing_logic_test.clj
- modules/cql/test/blaze/elm/compiler/test_util.clj
- modules/cql/test/blaze/elm/compiler/type_operators_test.clj
- modules/cql/test/blaze/elm/interval_spec.clj
- modules/cql/test/blaze/elm/literal.clj
- modules/cql/test/blaze/elm/quantity_spec.clj
- modules/cql/test/blaze/elm/quantity_test.clj
- modules/fhir-structure/src/blaze/fhir/spec/type/system.clj
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q37-overlaps-data.json
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q37-overlaps-query.cql
Also fixed the Overlaps operator and refactored some tests.
> Implement CQL FHIRHelpers ToInterval Function

- modules/cql/src/blaze/elm/compiler/reusing_logic.clj
- modules/cql/test/blaze/elm/compiler/reusing_logic_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q37-overlaps-data.json
We have to convert alle date times to CQL date times which are always local date times relative to now because all comparisons are done with local times without time zones.
> Fix CQL ToInterval Function

- .github/openid-auth-test/batch-bundle.json
- .github/scripts/authenticated-request.sh
- deps.edn
- modules/rest-api/src/blaze/rest_api.clj
- modules/rest-api/test/blaze/rest_api/middleware/auth_guard_test.clj
- test/blaze/system_test.clj
The auth-guard middleware has to be removed in the batch-handler.
Closes: #627
> Fix Authentication in Batch Requests

- docs/api/include.md
- docs/cql-queries/command-line.md
- docs/importing-data.md
- docs/performance/fhir-search.md
- docs/tooling.md
- evaluate-measure.sh
The script will now output a blazectl download command that can be used to download the subjects.
> Improve CQL Command Line Doc and Evaluate Script

- modules/byte-string/deps.edn
> Update Jackson Databind to v2.13.2.1

- modules/byte-string/deps.edn
> Update Jackson Databind to v2.13.2.2

- modules/rest-api/src/blaze/rest_api.clj
- modules/rest-api/src/blaze/rest_api/middleware/resource.clj
- modules/rest-api/src/blaze/rest_api/routes.clj
- modules/rest-api/test/blaze/rest_api/middleware/resource_test.clj
- modules/rest-api/test/blaze/rest_api_test.clj
- src/blaze/system.clj
- test/blaze/system_test.clj
If just not necessary, because resource parsing doesn't block. It's just
CPU load which can be handled by the Jetty pool.
> Remove Resource Parsing Pool

- modules/db-stub/src/blaze/db/api_stub.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/node_test.clj
- modules/rest-api/src/blaze/rest_api/middleware/ensure_form_body.clj
- modules/rest-api/src/blaze/rest_api/routes.clj
- modules/rest-api/test/blaze/rest_api_test.clj
- test/blaze/system_test.clj
> Return an Error on Incorrect Content-Type for Search Requests

- modules/byte-string/deps.edn
- modules/cassandra/deps.edn
- modules/cql/deps.edn
- modules/fhir-structure/deps.edn
- modules/http-client/deps.edn
- modules/rest-api/deps.edn
> Update Jackson to v2.13.3

- modules/db/src/blaze/db/impl/search_param/quantity.clj
- modules/db/test/blaze/db/impl/search_param/quantity_test.clj
> Fix Quantity Indexing without Value

- modules/cql/src/blaze/cql_translator.clj
- modules/cql/test/blaze/cql_translator_test.clj
> Remove English Locale to Prevent CQL Parsing Bug

- modules/rest-api/src/blaze/rest_api/capabilities.clj
> Remove Conditional Patch

- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/stratifier.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_test.clj
Before stata values of every type would be converted to string und put into "text" of the CodeableConcept of the stratum value. However for CodeableConcepts themself, we now return the value as is.
> Return CodeableConcepts as is for Strata

- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/stratifier.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_test.clj
In R5 stratum values can have different types. Quantity is one of them. This commit introduces the extension stratum-value that allows to output quantity values. The original value will still have a text component with a textual representation of the quantity.
> Add a Backport of R5 Quantity Stratum Values

- modules/rocksdb/src/blaze/db/kv/rocksdb.clj
The database options should not be closed after creating the database and there is no need to close them after the database is closed, because they are GC'ed automatically.
> Cleanup DBOptions Handling

- .github/workflows/build.yml
> Enable CI for Forks

- .github/workflows/build.yml
Fix CI stuff introduced by #941.
> Fix CI Stuff

- modules/rest-api/src/blaze/rest_api/capabilities.clj
- modules/rest-api/test/blaze/rest_api/capabilities_spec.clj
- modules/rest-api/test/blaze/rest_api/capabilities_test.clj
Add also include search param values.
> Add Profiles to Capability Statement

- .github/scripts/test-metrics.sh
- .github/workflows/build.yml
- docs/monitoring/blaze.json
- modules/metrics/src/blaze/metrics/core.clj
- modules/metrics/src/blaze/metrics/core_spec.clj
- modules/metrics/src/blaze/metrics/spec.clj
- modules/metrics/test/blaze/metrics/core_test.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/impl.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/metrics.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/metrics/spec.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/protocols.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/spec.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb_spec.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb/impl_test.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb/metrics_spec.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb/metrics_test.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
- resources/blaze.edn
The metric is called blaze_rocksdb_table_reader_usage_bytes.
> Add RocksDB Table Reader Usage Metric

- modules/rocksdb/src/blaze/db/kv/rocksdb.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/impl.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb/impl_spec.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb/impl_test.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
- resources/blaze.edn
Also remove the block cache from the resource database because it's not worth it.
> Make Block Cache Optional

- modules/interaction/src/blaze/interaction/search/params.clj
- modules/interaction/test/blaze/interaction/search/params_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
422 Unprocessable Content is definitely wrong, because there is no request entity to process.
> Use 404 Status Code on Not Found Tokens

- modules/fhir-structure/.clj-kondo/config.edn
- modules/interaction/src/blaze/interaction/transaction/bundle/links.clj
- modules/interaction/test/blaze/interaction/transaction/bundle/links_test.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
> Resolve Relative Attachment.url Values Like References

- modules/db/test/blaze/db/tx_log/local_test.clj
> Improve Robustness of New Queue Test

- modules/operation-patient-everything/src/blaze/operation/patient/everything.clj
- modules/operation-patient-everything/test/blaze/operation/patient/everything_test.clj
> Improve Error Handling on Non-Existing Patient

- .github/workflows/build.yml
We now test Java 11, 17 and 21.
> Upgrade Java version in CI from 20 to 21

- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q50-specimen-condition-reference.cql
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q50-specimen-condition-reference.json
This test is an example from the MII Core Dataset.
> Add CQL Specimen Diagnose Reference Test

- .github/scripts/download-resources-query-sort.sh
- .github/workflows/build.yml
- docs/api.md
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db-tx-log-kafka/test/blaze/db/tx_log/kafka_test.clj
- modules/db/src/blaze/db/impl/search_param/token.clj
- modules/db/src/blaze/db/node.clj
- modules/db/src/blaze/db/search_param_registry.clj
- modules/db/src/blaze/db/search_param_registry_spec.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/search_param/token_test.clj
- modules/db/test/blaze/db/node/resource_indexer_test.clj
- modules/db/test/blaze/db/search_param_registry_test.clj
- modules/fhir-path/test/blaze/fhir_path_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/rest-api/src/blaze/rest_api/capabilities.clj
- modules/rest-api/test/blaze/rest_api/capabilities_test.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
> Implement FHIR Search Sorting by ID

- modules/cql/src/blaze/cql_translator.clj
- modules/cql/test/blaze/cql_translator_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
> Improve Error Reporting on CQL Parsing Problems

- cljfmt.edn
- docs/implementation/database.md
- modules/db-stub/src/blaze/db/api_stub.clj
- modules/db/src/blaze/db/cache_collector.clj
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/impl/index/compartment/resource.clj
- modules/db/src/blaze/db/impl/index/t_by_instant.clj
- modules/db/src/blaze/db/impl/index/tx_error.clj
- modules/db/src/blaze/db/node.clj
- modules/db/src/blaze/db/node/tx_indexer/verify.clj
- modules/db/src/blaze/db/node/version.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/node/resource_indexer_test.clj
- modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
- modules/interaction/test/blaze/interaction/create_test.clj
- modules/metrics/test/blaze/metrics/core_test.clj
- modules/page-store/src/blaze/page_store/local.clj
- modules/rest-api/src/blaze/rest_api/middleware/metrics.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/metrics.clj
- modules/thread-pool-executor-collector/src/blaze/thread_pool_executor_collector.clj
The changes are ported from the CQL Cache branch in order to reduce the changes it will introduce.
> Port Refactorings and Doc Improvements

- .github/scripts/check-capability-statement-filtered.sh
- .github/workflows/build.yml
- docs/api.md
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/rest-api/src/blaze/rest_api/capabilities.clj
- modules/rest-api/test/blaze/rest_api/capabilities_test.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/src/blaze/handler/fhir/util_spec.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
- modules/rest-util/test/blaze/middleware/fhir/db_test.clj
> Support filtering for elements in CapabilityStatement

- .github/scripts/patient-everything.sh
- .github/scripts/patient-everything/X79746011X-type-counts.csv
- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/api_spec.clj
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/impl/db.clj
- modules/db/src/blaze/db/search_param_registry.clj
- modules/db/src/blaze/db/search_param_registry_spec.clj
- modules/db/test/blaze/db/api_test.clj
- modules/fhir-test-util/src/blaze/fhir/spec/generators.clj
- modules/operation-patient-everything/src/blaze/operation/patient/everything.clj
> Include Supporting Resources in Patient $everything

- .github/workflows/build.yml
We need to update upload and download together.
> Update actions/*-artifact action to v4

- modules/cql/src/blaze/elm/quantity.clj
- modules/cql/src/blaze/elm/ratio.clj
- modules/cql/test/blaze/elm/compiler/comparison_operators_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q33-incompatible-quantities.cql
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q33-incompatible-quantities.json
> Fix Quantity Comparison with Incompatible Units Fails

- .clj-kondo/root/config.edn
- .github/scripts/check-capability-statement-caching.sh
- .github/workflows/build.yml
- modules/rest-api/src/blaze/rest_api.clj
- modules/rest-api/src/blaze/rest_api/capabilities.clj
- modules/rest-api/src/blaze/rest_api/header.clj
- modules/rest-api/src/blaze/rest_api/middleware/output.clj
- modules/rest-api/test/blaze/rest_api/capabilities/spec.clj
- modules/rest-api/test/blaze/rest_api/capabilities_test.clj
- modules/rest-api/test/blaze/rest_api/header_spec.clj
- modules/rest-api/test/blaze/rest_api/header_test.clj
- modules/rest-api/test/blaze/rest_api/middleware/output_test.clj
- modules/rest-api/test/blaze/rest_api_test.clj
- modules/spec/src/blaze/spec.clj
- src/blaze/system.clj
- test/blaze/system_test.clj
> Enable Caching for the Capability Statement

- modules/db/src/blaze/db/impl/search_param/token.clj
- modules/db/test/blaze/db/api_test.clj
> FHIR Search _id Queries Should Not Return Deleted Patients

- .github/workflows/build.yml
- modules/db/src/blaze/db/impl/index.clj
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
> Fix FHIR Search Combination of Sorting and Token Search

- .github/scripts/search-observation-profile-version.sh
- .github/scripts/search-observation-profile.sh
- docs/api.md
- modules/async/test/blaze/async/comp_test.clj
- modules/db/src/blaze/db/impl/codec.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/composite/common.clj
- modules/db/src/blaze/db/impl/search_param/token.clj
- modules/db/src/blaze/db/impl/search_param/util.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/search_param/token_test.clj
- modules/db/test/blaze/db/impl/search_param/util_spec.clj
- modules/db/test/blaze/db/impl/search_param/util_test.clj
- modules/db/test/blaze/db/node/resource_indexer_test.clj
- modules/interaction/src/blaze/interaction/util.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/operation-patient-everything/test/blaze/operation/patient/everything_test.clj
The search will only work for newly created or updated resources until https://github.com/samply/blaze/issues/1442 is available.
Closes: #1418
> Implement Below Modifier for Canonical References

- modules/db/src/blaze/db/impl/index/resource_as_of.clj
- modules/db/test/blaze/db/api_test.clj
- modules/kv/src/blaze/db/kv.clj
> Fix Error While Reading Non-Existent Resource

- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q28-relationship-procedure-condition.cql
In is only used for multiple codes and not for one single code.
> Use Equivalent instead of In in Retrieve

- .github/scripts/admin-api/column-family-metadata.sh
- .github/workflows/build.yml
- modules/rocksdb/deps.edn
Have to downgrade RocksDB to v8.10.2 because there is an error in column family metadata.
> Add First Admin API Integration Tests

- .github/scripts/download-observations-of-all-encounters.sh
- .github/workflows/build.yml
This integration test should ensure that we can query for more than 4000 references.
> Add Test Download Observations of all Encounters using ID's

- modules/admin-api/src/blaze/admin_api.clj
- modules/admin-api/test/blaze/admin_api_test.clj
> Fix Startup Error when Using in-memory Storage

- modules/rocksdb/src/blaze/db/kv/rocksdb.clj
- modules/rocksdb/src/blaze/db/kv/rocksdb/impl.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb/impl_spec.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb/impl_test.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
Allow RocksDB instances without statistics.
> Make RocksDB Statistics Optional

- modules/interaction/src/blaze/interaction/util.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/interaction/test/blaze/interaction/util_test.clj
- modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
> Fix _id Search with Sort Clause

- modules/frontend/src/lib/resource/json/primitive-value.svelte
- modules/frontend/src/lib/resource/json/property.svelte
- modules/frontend/src/lib/resource/primitive-value.svelte
- modules/frontend/src/lib/resource/resource-card.test.ts
- modules/frontend/src/lib/resource/resource-card.ts
> Fix Rendering of Primitive Extensions

- .github/scripts/admin-api/create-invalid-jobs.sh
- .github/scripts/jobs/re-index/create-invalid-job.sh
- .github/workflows/build.yml
- Dockerfile
- job-ig/Makefile
- modules/admin-api/deps.edn
- modules/admin-api/resources/blaze/admin_api/StructureDefinition-CompactJob.json
- modules/admin-api/src/blaze/admin_api.clj
- modules/admin-api/src/blaze/admin_api/validation.clj
- modules/admin-api/test/blaze/admin_api_test.clj
- modules/page-store/src/blaze/page_store/local.clj
- modules/rest-util/deps.edn
> Remove Need for FHIR Validator Local Package Cache

- modules/admin-api/deps.edn
> Update commons-compress to v0.16.1

- modules/db/src/blaze/db/impl/search_param/token.clj
- modules/db/test/blaze/db/api_test.clj
Resolves hash collisions for identifier searches by filtering the results after index scan.
Closes: #1685
> Fix Delivering too Many Search Results in Some Cases

- .github/scripts/search-tag.sh
- .github/workflows/build.yml
- modules/db/test/blaze/db/api_test.clj
- modules/interaction/src/blaze/interaction/util.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Enable FHIR Search by _tag

- .github/workflows/build.yml
- docs/package-lock.json
- docs/package.json
Also updated page dependencies.
> Fix Page Building

- .github/scripts/download-resources-query-sort.sh
- .github/scripts/download-resources-query.sh
I can't reproduce the error locally, so I just added an echo of all the last updated values in case of error.
> Output Last Updated Values in Case of Error

- docs/tuning-guide.md
Also added CQL cache size recommendations.
> Add Smaller System Sizes to the Tuning Guide

- modules/thread-pool-executor-collector/test/blaze/thread_pool_executor_collector_test.clj
Introduced another sleep between scheduling the future and collecting the metrics.
> Improve Stability of Thread Pool Executor Test

- modules/fhir-structure/test/blaze/fhir/spec/generators.clj
- modules/rest-api/src/blaze/rest_api/capabilities_handler.clj
- modules/rest-api/test/blaze/rest_api/capabilities_handler_test.clj
> Add Patient Compartment Definition to Capability Statement

- .github/scripts/delete.sh
- .github/scripts/util.sh
- modules/rest-util/src/blaze/middleware/fhir/output.clj
- modules/rest-util/test/blaze/middleware/fhir/output_test.clj
> Remove Content-Type Header from Empty Responses

- .github/scripts/cancel-async.sh
- .github/scripts/count-async.sh
> Ensure that Async Status Endpoint uses OperationOutcome

- .github/scripts/check-delete-succeeds-after-referring-resource-is-deleted.sh
- .github/workflows/build.yml
Test that a delete of a previously referenced resource succeeds after deletion of the referring resource.
> Add Delete Integration Test

- .github/distributed-test/docker-compose.yml
- .github/workflows/build.yml
Changes take into account that the CI runner has now 4 cores and 16 GiB RAM.
> Improve CI Perf of Distributed Integration Test

- modules/cql/src/blaze/elm/compiler/queries.clj
- modules/cql/test/blaze/elm/compiler/queries_test.clj
- modules/db/src/blaze/db/impl/index.clj
- modules/db/test/blaze/db/impl/index_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q60-medication.cql
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q60-medication.json
> Fix Error While Optimizing CQL Queries

- modules/coll/src/blaze/coll/core.clj
- modules/coll/test/blaze/coll/core_test.clj
- modules/cql/src/blaze/elm/compiler/library.clj
- modules/cql/src/blaze/elm/compiler/library_spec.clj
- modules/cql/src/blaze/elm/compiler/list_operators.clj
- modules/cql/src/blaze/elm/compiler/macros.clj
- modules/cql/test/blaze/elm/compiler/library_test.clj
- modules/cql/test/blaze/elm/compiler/list_operators_test.clj
- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
> Optimize CQL Exists over Empty Lists into False

- cljfmt.edn
- modules/cql/src/blaze/elm/compiler/logical_operators.clj
- modules/cql/src/blaze/elm/compiler/macros.clj
- modules/cql/test/blaze/elm/compiler/arithmetic_operators_test.clj
- modules/cql/test/blaze/elm/compiler/conditional_operators_test.clj
- modules/cql/test/blaze/elm/compiler/date_time_operators_test.clj
- modules/cql/test/blaze/elm/compiler/interval_operators_test.clj
- modules/cql/test/blaze/elm/compiler/library_test.clj
- modules/cql/test/blaze/elm/compiler/list_operators_test.clj
- modules/cql/test/blaze/elm/compiler/logical_operators_test.clj
- modules/cql/test/blaze/elm/compiler/nullological_operators_test.clj
- modules/cql/test/blaze/elm/compiler/reusing_logic_test.clj
- modules/cql/test/blaze/elm/compiler/string_operators_test.clj
- modules/cql/test/blaze/elm/compiler/test_util.clj
- modules/cql/test/blaze/elm/compiler/type_operators_test.clj
- modules/cql/test/data_readers.clj
> Optimize CQL Logical Expressions

- .github/workflows/build.yml
- CHANGELOG.md
- modules/cql/src/blaze/elm/compiler.clj
- modules/cql/src/blaze/elm/compiler/conditional_operators.clj
- modules/cql/src/blaze/elm/compiler/core.clj
- modules/cql/src/blaze/elm/compiler/date_time_operators.clj
- modules/cql/src/blaze/elm/compiler/external_data.clj
- modules/cql/src/blaze/elm/compiler/function.clj
- modules/cql/src/blaze/elm/compiler/library.clj
- modules/cql/src/blaze/elm/compiler/library_spec.clj
- modules/cql/src/blaze/elm/compiler/list_operators.clj
- modules/cql/src/blaze/elm/compiler/logical_operators.clj
- modules/cql/src/blaze/elm/compiler/macros.clj
- modules/cql/src/blaze/elm/compiler/nullological_operators.clj
- modules/cql/src/blaze/elm/compiler/queries.clj
- modules/cql/src/blaze/elm/compiler_spec.clj
- modules/cql/test/blaze/elm/compiler/conditional_operators_test.clj
- modules/cql/test/blaze/elm/compiler/external_data_test.clj
- modules/cql/test/blaze/elm/compiler/library_test.clj
- modules/cql/test/blaze/elm/compiler/list_operators_test.clj
- modules/cql/test/blaze/elm/compiler/queries_test.clj
- modules/cql/test/blaze/elm/compiler/reusing_logic_test.clj
- modules/cql/test/blaze/elm/compiler/test_util.clj
- modules/db/src/blaze/db/api.clj
- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
> Optimize CQL by Removing Retrieve Expressions with Non-Matching Codes

- modules/db/src/blaze/db/impl/search_param/composite.clj
- modules/db/src/blaze/db/impl/search_param/core.clj
- modules/db/src/blaze/db/impl/search_param/token.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/impl/search_param/token_test.clj
> Support Search Parameters with Type uri and Data Type url

- modules/db/test/blaze/db/api_test.clj
- modules/fhir-path/src/blaze/fhir_path.clj
- modules/fhir-path/test/blaze/fhir_path_test.clj
> Add Hack to allow FHIRPath As Type Specifier on Collections

- .github/scripts/create-patient-with-ancient-birth-year.sh
- .github/workflows/build.yml
- modules/fhir-structure/java/blaze/fhir/spec/type/system/DateTimeYear.java
- modules/fhir-structure/java/blaze/fhir/spec/type/system/DateYear.java
- modules/fhir-structure/test/blaze/fhir/spec/generators.clj
- modules/fhir-structure/test/blaze/fhir/spec/type_test.clj
> Fix Parsing of Dates starting with a Zero in the Year Component

- .github/scripts/patient-everything-paged-date-range.sh
- .github/workflows/build.yml
- modules/operation-patient-everything/src/blaze/operation/patient/everything.clj
- modules/operation-patient-everything/test/blaze/operation/patient/everything_test.clj
> Patient $everything Ignores Query Params when Paging

- DEVELOPMENT.md
- Makefile
- deps.edn
- dev/blaze/dev.clj
For now, big documentation changes will be part of a separate PR.
> Add nREPL support

- DEVELOPMENT.md
- docs/deployment/README.md
TODO: make Release Checklist use current release workflow
Thanks to FastChat!
https://github.com/lm-sys/FastChat
https://lmarena.ai/
> Overhaul DEVELOPMENT

- .github/workflows/build.yml
- modules/byte-string/deps.edn
- modules/db/deps.edn
With two exceptions in module byte-string and db because of Cloverage reflection issues.
> Update Clojure to v1.12.0.1479

- modules/fhir-client/Makefile
- modules/fhir-client/src/blaze/fhir_client.clj
- modules/fhir-client/src/blaze/fhir_client_spec.clj
- modules/fhir-client/test/blaze/fhir_client_test.clj
We need that functions in #1382 for the Jepsen tests.
> Add delete-history and history-instance Functions

- .github/scripts/conditional-delete-type/delete-all-resources-of-type.sh
- .github/scripts/patient-purge.sh
- .github/workflows/build.yml
- deps.edn
- docs/api.md
- docs/api/operation-patient-purge.md
- docs/implementation/database.md
- modules/db-tx-log/src/blaze/db/tx_log/spec.clj
- modules/db/src/blaze/db/node/transaction.clj
- modules/db/src/blaze/db/node/tx_indexer/expand.clj
- modules/db/src/blaze/db/node/tx_indexer/verify.clj
- modules/db/src/blaze/db/spec.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/node/tx_indexer/expand_test.clj
- modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
- modules/operation-patient-purge/.clj-kondo/config.edn
- modules/operation-patient-purge/Makefile
- modules/operation-patient-purge/README.md
- modules/operation-patient-purge/deps.edn
- modules/operation-patient-purge/src/blaze/operation/patient/purge.clj
- modules/operation-patient-purge/test/blaze/operation/patient/purge_test.clj
- modules/operation-patient-purge/tests.edn
- modules/rest-api/src/blaze/rest_api/routes.clj
- modules/rest-api/src/blaze/rest_api/spec.clj
- modules/rest-api/test/blaze/rest_api/routes_test.clj
- modules/rest-util/src/blaze/middleware/fhir/resource.clj
- modules/rest-util/test/blaze/middleware/fhir/resource_test.clj
- resources/blaze.edn
> Implement Operation Patient $purge

- docs/performance/fhir-search.md
- docs/performance/fhir-search/code-date-patient-search.sh
- docs/performance/fhir-search/code-patient-search.sh
- docs/performance/fhir-search/util.sh
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/search_param_registry_test.clj
> Improve FHIR Search Performance with Subject References

- modules/frontend/package-lock.json
- modules/frontend/package.json
> Override Cookie Dependency to v1.0.0

- .github/value-set-expand/expand-all.sh
- modules/operation-code-system-validate-code/test/blaze/fhir/operation/code_system/validate_code_test.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/default.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/sct.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/ucum.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/util.clj
- modules/terminology-service/src/blaze/terminology_service/local/value_set.clj
- modules/terminology-service/src/blaze/terminology_service/local/value_set/expand.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
Removed the phrase "with URL".
> Simplify Terminology Service Error Messages

- modules/db/src/blaze/db/node.clj
- modules/db/test/blaze/db/api_test.clj
> Fix Optimised FHIR Search with Subject References

- modules/rest-util/test/blaze/middleware/fhir/output_test.clj
It was not clear that, no matter what is the requested content type, as long as it is a non-FHIR one, the actual content type will be that of the resource.
> Improve Binary Download tests

- modules/rest-util/test/blaze/middleware/fhir/resource_test.clj
Make sure we are testing the same things in both cases.
> Improve resource tests: JSON vs. XML (Preparation for #2126)

- modules/terminology-service/src/blaze/terminology_service/local.clj
In oder to be able to generate the TerminologyCapabilities fast if many CodeSystem resources exist, we need to have them in memory. Otherwise loading especially large code systems like ICD-10 take too long.
Later we can properly remove that if we store summary versions of resources separately.
> Load Code Systems At Startup

- docs/api/interaction/history-instance.md
- docs/api/interaction/history-system.md
- docs/api/interaction/history-type.md
- modules/interaction/src/blaze/interaction/history/instance.clj
- modules/interaction/src/blaze/interaction/history/system.clj
- modules/interaction/src/blaze/interaction/history/type.clj
- modules/interaction/src/blaze/interaction/history/util.clj
- modules/interaction/test/blaze/interaction/history/util_test.clj
> Fix Negative Total Values in History Bundles Generated

- docs/.vitepress/config.ts
- docs/terminology-service.md
- docs/terminology-service/fhir.md
- docs/terminology-service/loinc.md
- docs/terminology-service/snomed-ct.md
- docs/terminology-service/ucum.md
- modules/terminology-service/src/blaze/terminology_service/local/code_system/sct/filter/equals.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
Also improved the terminology service documentation.
> Add SNOMED CT Equals Child Filter

- docs/deployment/full-standalone.md
- modules/openid-auth/.clj-kondo/config.edn
- modules/openid-auth/src/blaze/openid_auth.clj
- modules/openid-auth/src/blaze/openid_auth/impl.clj
- modules/openid-auth/test/blaze/openid_auth/impl_test.clj
- modules/openid-auth/test/blaze/openid_auth_test.clj
> Improve Error Message while Fetching the Public Key

- Dockerfile
> Fix ARM64 Docker Build

- modules/admin-api/src/blaze/admin_api/spec.clj
- modules/admin-api/test/blaze/admin_api_test.clj
- modules/frontend/src/routes/__admin/+layout.ts
- modules/frontend/src/routes/__admin/setting-row.svelte
- src/blaze/system.clj
- test/blaze/system_test.clj
> Mask Settings containing Secrets in Admin API

- docs/api/interaction/delete.md
- docs/api/interaction/update.md
- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/api_spec.clj
- modules/db/src/blaze/db/node/tx_indexer/verify.clj
- modules/db/test/blaze/db/api_test.clj
> Prevent Internal System Resources from Change

- .github/scripts/check-code-system-read-only.sh
- .github/workflows/build.yml
- modules/terminology-service/src/blaze/terminology_service/local/code_system/bcp_13.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/loinc.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/loinc/context.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/sct/context.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/ucum.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
> Prevent Internal Code System Resources from Change

- .github/actions/speicherwolke-download/action.yml
- .github/validation/validate.sh
- .github/workflows/build.yml
> Use Full SCT Release in Tests

- modules/cql/src/blaze/elm/compiler/interval_operators.clj
- modules/cql/src/blaze/elm/interval.clj
- modules/cql/test/blaze/elm/compiler/library_test.clj
- modules/cql/test/blaze/elm/compiler/structured_values_test.clj
- modules/cql/test/blaze/elm/interval_spec.clj
> Fix Low and High Property Access on Interval

- docs/terminology-service/loinc.md
- modules/terminology-service/src/blaze/terminology_service/local/code_system/loinc/filter/equals.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
> Add LOINC Answer List Property answer-list

- docs/api/operation/code-system-validate-code.md
- docs/api/operation/value-set-expand.md
- docs/api/operation/value-set-validate-code.md
- docs/terminology-service/fhir.md
- docs/terminology-service/loinc.md
- docs/terminology-service/resource-resolution.md
- docs/terminology-service/snomed-ct.md
- modules/terminology-service/src/blaze/terminology_service/local/priority.clj
- modules/terminology-service/test/blaze/terminology_service/local/priority_test.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
> Document Terminology Resource Resolution

- DEVELOPMENT.md
- specifically with instructions about WSL & Git line endings etc.
> Improve DEVELOPMENT.md.

- modules/anomaly/src/blaze/anomaly.clj
Profiling the new parser has shown that about 15% is spend detecting whether a value is an anomaly or not. Especially records like Coding or Quantity have poor performance on keyword lookup. The new version first tests that the anomaly is actually a real Clojure map (APersistentMap) which a record isn't and than even uses .containsKey to save recurring type checks.
Closes: #2506
> Improve Anomaly Detection Performance

- modules/terminology-service/sct-release-versions.sh
- modules/terminology-service/src/blaze/terminology_service/local/code_system/sct/context.clj
- modules/terminology-service/test/blaze/terminology_service/local/code_system/sct/context_test.clj
- modules/terminology-service/test/blaze/terminology_service/local/code_system/sct_test.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
> Fix SNOMED CT Versions

- modules/terminology-service/src/blaze/terminology_service/local/code_system/sct/context.clj
- modules/terminology-service/test/blaze/terminology_service/local/code_system/sct/context_test.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
> Fix Module Dependency Resolution

- modules/fhir-structure/.clj-kondo/config.edn
- modules/fhir-structure/.clj-kondo/macros.clj
- modules/fhir-structure/src/blaze/fhir/spec.clj
- modules/fhir-structure/src/blaze/fhir/spec/spec.clj
- modules/fhir-structure/src/blaze/fhir/spec_spec.clj
- modules/fhir-structure/test/blaze/fhir/spec/generators.clj
- modules/fhir-structure/test/blaze/fhir/spec_test.clj
- modules/fhir-structure/tests.edn
> Implement Partial Summary Pull in Conform CBOR

- .github/workflows/build.yml
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/interaction/src/blaze/interaction/search_compartment.clj
- modules/interaction/src/blaze/interaction/search_system.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/search/params_spec.clj
- modules/interaction/test/blaze/interaction/search/params_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system.clj
> Return Summary Variant of ValueSet and CodeSystem Resources by Default

- .github/terminology-tests/validation-version.sh
- .github/workflows/build.yml
- modules/operation-value-set-validate-code/src/blaze/fhir/operation/value_set/validate_code.clj
- modules/operation-value-set-validate-code/test/blaze/fhir/operation/value_set/validate_code_test.clj
- modules/terminology-service/src/blaze/terminology_service/local.clj
- modules/terminology-service/src/blaze/terminology_service/local/value_set/expand.clj
- modules/terminology-service/src/blaze/terminology_service/local/value_set/util.clj
- modules/terminology-service/src/blaze/terminology_service/local/value_set/validate_code.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
> Support system-version Parameter on ValueSet $validate-code

- modules/interaction/src/blaze/interaction/history/instance.clj
- modules/interaction/src/blaze/interaction/history/system.clj
- modules/interaction/src/blaze/interaction/history/type.clj
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/interaction/src/blaze/interaction/search_system.clj
- modules/interaction/test/blaze/interaction/history/instance_test.clj
- modules/interaction/test/blaze/interaction/history/system_test.clj
- modules/interaction/test/blaze/interaction/history/type_test.clj
- modules/interaction/test/blaze/interaction/search_compartment_test.clj
- modules/interaction/test/blaze/interaction/search_system_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/operation-patient-everything/test/blaze/operation/patient/everything_test.clj
- modules/page-id-cipher/src/blaze/page_id_cipher/spec.clj
- modules/page-store/src/blaze/page_store/spec.clj
- modules/page-store/test/blaze/page_store/local_test.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/src/blaze/handler/fhir/util_spec.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
> Support Summary Pull at Search System and History Interactions

- modules/cql/src/blaze/elm/compiler/structured_values.clj
- modules/cql/test/blaze/elm/compiler/structured_values_test.clj
- modules/cql/test/blaze/elm/compiler/test_util.clj
- modules/cql/test/blaze/elm/compiler/type_operators_test.clj
- modules/fhir-structure/resources/data_readers.clj
- modules/fhir-structure/src/blaze/fhir/spec/type.clj
- modules/fhir-structure/src/blaze/fhir/spec/type/system.clj
- modules/fhir-structure/src/blaze/fhir/spec/type/system_spec.clj
- modules/fhir-structure/src/blaze/fhir/spec/type_spec.clj
- modules/fhir-structure/test/blaze/fhir/spec/type/system_test.clj
- modules/fhir-structure/test/blaze/fhir/spec/type_test.clj
> Introduce Separate Primitive FHIR Date and DateTime Types

- modules/operation-code-system-validate-code/src/blaze/fhir/operation/code_system/validate_code.clj
- modules/operation-value-set-expand/src/blaze/fhir/operation/value_set/expand.clj
- modules/operation-value-set-validate-code/src/blaze/fhir/operation/value_set/validate_code.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/src/blaze/handler/fhir/util_spec.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
Only pull the summary variant of CodeSystem and ValueSet resources in order to obtain the URL.
> Improve Terminology Operation Performance

- .github/scripts/conditional-delete-type/delete-multiple-types-in-transaction.sh
- .github/workflows/build.yml
- modules/db/test/blaze/db/api_test.clj
- modules/interaction/src/blaze/interaction/transaction/bundle.clj
- modules/interaction/test/blaze/interaction/transaction/bundle_spec.clj
- modules/interaction/test/blaze/interaction/transaction/bundle_test.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/src/blaze/handler/fhir/util_spec.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
> Fix Conditional Delete in Transaction

- .github/scripts/generate-large-binary-resource.sh
- .github/workflows/build.yml
- modules/fhir-structure/src/blaze/fhir/spec.clj
> Remove Jackson Maximum String Length

- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
> Fix Thread Deadlock on Large Batches

- .github/scripts/batch-metadata.sh
- .github/scripts/batch.sh
- .github/scripts/check-date-search.sh
- .github/scripts/conditional-delete-type/check-referential-integrity-violated.sh
- .github/scripts/create-patient-batch.sh
- .github/scripts/util.sh
- .github/workflows/build.yml
Also added Create Patient in Batch test.
> Refactor Integration Tests

- modules/db/src/blaze/db/impl/search_param/token.clj
> Fix False Positives while Searching for References

- modules/frontend/package-lock.json
- modules/frontend/package.json
> Remove Adapters Auto and Static from Frontend

- .github/workflows/build.yml
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
> Revert Summary of Value Sets and Code Systems by Default

- .github/scripts/install-validator.sh
- docs/terminology-service/validation.md
- job-ig/Makefile
- modules/job-async-interaction/Makefile
This is the direct URL. The old one was from the wrapper.
> Update Validator Download URL

- .github/workflows/scorecard.yml
Removed running on pull requests.
> Run Scorecard Analysis only on Main Branch

- docs/architecture.md
- docs/cql-queries/api.md
- docs/deployment/full-standalone.md
- docs/frontend.md
- docs/implementation/database.md
- docs/implementation/fhir-data-model.md
- fix typos
- other improvements to clarify the meaning
> Improve documentation.

- .github/workflows/build.yml
Default Trivy DB Images are not affected by rate limiting anymore.
> Remove Trivy DB Config

- .github/scripts/install-validator.sh
- .github/validation/validate.sh
- docs/terminology-service/validation.md
> Update FHIR Validator to v6.5.21

- .github/scripts/compact-unknown-database.sh
- .github/scripts/compact.sh
- .github/scripts/count-async.sh
- .github/scripts/evaluate-measure-async.sh
- .github/scripts/evaluate-measure-subject-list-async.sh
- .github/workflows/build.yml
- modules/interaction/src/blaze/interaction/transaction.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
- modules/job-async-interaction/src/blaze/job/async_interaction.clj
- modules/job-async-interaction/src/blaze/job/async_interaction/request.clj
- modules/job-async-interaction/src/blaze/job/async_interaction/util.clj
- modules/job-async-interaction/test/blaze/job/async_interaction/request_test.clj
- modules/job-async-interaction/test/blaze/job/async_interaction/util_test.clj
- modules/rest-util/src/blaze/handler/fhir/util.clj
- modules/rest-util/src/blaze/handler/util.clj
- modules/rest-util/test/blaze/handler/fhir/util_test.clj
- modules/rest-util/test/blaze/handler/util_test.clj
> Implement Async Request Pattern for POST Requests

- .github/scripts/check-summary-mode.sh
- .github/scripts/util.sh
- .github/workflows/build.yml
- modules/interaction/src/blaze/interaction/search/params.clj
- modules/interaction/src/blaze/interaction/search_compartment.clj
- modules/interaction/src/blaze/interaction/search_system.clj
- modules/interaction/src/blaze/interaction/search_type.clj
- modules/interaction/test/blaze/interaction/history/instance_test.clj
- modules/interaction/test/blaze/interaction/history/system_test.clj
- modules/interaction/test/blaze/interaction/history/type_test.clj
- modules/interaction/test/blaze/interaction/search/params_spec.clj
- modules/interaction/test/blaze/interaction/search/params_test.clj
- modules/interaction/test/blaze/interaction/search_system_test.clj
- modules/interaction/test/blaze/interaction/search_type_test.clj
- modules/interaction/test/blaze/interaction/test_util.clj
> Support Summary Mode Search Type

- modules/cql/src/blaze/elm/compiler/structured_values.clj
- modules/cql/test/blaze/elm/compiler/structured_values_test.clj
> Fix missing Value Access in Some DateTime Types

- .github/scripts/check-terminology-capabilities.sh
- .github/workflows/build.yml
- modules/terminology-service/src/blaze/terminology_service/local.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/bcp_47.clj
- modules/terminology-service/src/blaze/terminology_service/local/code_system/core.clj
- modules/terminology-service/src/blaze/terminology_service/local/spec.clj
- modules/terminology-service/test/blaze/terminology_service/local/code_system/bcp_47_test.clj
- modules/terminology-service/test/blaze/terminology_service/local_test.clj
- resources/blaze.edn
closes #2505
- show script and region with locale
- add missing tests for bcp-13
> Implement BCP 47 Code System

- docs/deployment.md
Just filled in the output from v1.0.0.
> Improve Docker Image verification Docu

- modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
- modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
> Search for text/cql Content in Library

- .github/scripts/transaction-relative-references.sh
- .github/workflows/build.yml
- docs/api/interaction/transaction.md
- modules/interaction/src/blaze/interaction/transaction/bundle/links.clj
- modules/interaction/test/blaze/interaction/transaction/bundle/links_spec.clj
- modules/interaction/test/blaze/interaction/transaction/bundle/links_test.clj
> Support Resolving Relative References in Transaction Bundles

- modules/interaction/src/blaze/interaction/transaction.clj
- modules/interaction/test/blaze/interaction/transaction_test.clj
We can't use `with-open` to close the Batch DB if we return a future.
> Fix Closing of Batch DB

- modules/frontend-e2e/src/fhir.spec.ts
- modules/frontend/src/lib/history/badge.svelte
- modules/frontend/src/lib/history/subsetted-badge.svelte
> Mark Resources in Normal UI View as Subsetted

- modules/frontend-e2e/README.md
- modules/frontend-e2e/src/fhir.spec.ts
Just choosing the first patient and assuming that it has on official badge on it's name doesn't work because the patient IDs are random.
Choosing a certain patient solves the problem.
> Fix Flaky Frontend Test

- modules/db-protocols/src/blaze/db/impl/protocols.clj
- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/api_spec.clj
- modules/db/src/blaze/db/impl/batch_db.clj
- modules/db/src/blaze/db/impl/db.clj
- modules/db/src/blaze/db/node.clj
- modules/db/src/blaze/db/node/tx_indexer.clj
- modules/db/src/blaze/db/node/tx_indexer/verify.clj
- modules/db/test/blaze/db/api_test.clj
- modules/db/test/blaze/db/node/tx_indexer/verify/spec.clj
- modules/db/test/blaze/db/node/tx_indexer/verify_spec.clj
- modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
- modules/db/test/blaze/db/node/tx_indexer_spec.clj
> Compile Read-Only Matcher Upfront

- modules/db/src/blaze/db/api.clj
- modules/db/src/blaze/db/api_spec.clj
- modules/db/src/blaze/db/impl/batch_db/patient_everything.clj
- modules/db/src/blaze/db/impl/index/compartment/resource.clj
- modules/db/src/blaze/db/impl/index/compartment/search_param_value_resource.clj
- modules/db/src/blaze/db/impl/index/resource_as_of.clj
- modules/db/src/blaze/db/impl/index/resource_handle.clj
- modules/db/src/blaze/db/impl/index/resource_search_param_value.clj
- modules/db/src/blaze/db/impl/index/search_param_value_resource.clj
- modules/db/src/blaze/db/impl/search_param.clj
- modules/db/src/blaze/db/impl/search_param/date.clj
- modules/db/src/blaze/db/impl/search_param/quantity.clj
- modules/db/src/blaze/db/impl/search_param/string.clj
- modules/db/src/blaze/db/impl/search_param/token.clj
- modules/db/src/blaze/db/impl/search_param/util.clj
- modules/db/test/blaze/db/api_test.clj
> DB Cleanup

- .github/workflows/build.yml
- docs/performance/fhir-search.md
- docs/performance/fhir-search/category-date-search.sh
- modules/rocksdb/src/blaze/db/kv/rocksdb.clj
Also added mem-tables to RocksDB estimate-scan-size in order to improve query plan stability.
> Add Category and Date Search Performance Tests

- modules/fhir-path/src/blaze/fhir_path.clj
- modules/fhir-path/test/blaze/fhir_path_test.clj
> Fix FHIRPath Indexer Expression

- modules/fhir-structure/src/blaze/fhir/spec/resource.clj
- modules/fhir-structure/test/blaze/fhir/spec_test.clj
> Fix Regression In Resource Memory Consumption
