project.clj, src/blaze/terminology_service/extern.clj
Also excluded netty-all from datomic-free in order to have only one set of Netty
JAr's in classpath.
=> Disable Name Resolution in Proxy Mode

project.clj, src/blaze/handler/app.clj, src/blaze/handler/fhir/core.clj, src/blaze/middleware/authentication.clj, src/blaze/middleware/guard.clj, src/blaze/system.clj, test/blaze/handler/app_test.clj, test/blaze/handler/fhir/core_test.clj, test/blaze/middleware/authentication_test.clj
To add authentication to Blaze, I created a middleware that will try to verify a Signed JWT when the environment variable `OPENID_PROVIDER_URL` is a non-empty string. If `OPENID_PROVIDER_URL` is nil or an empty string, the request will be handled normally.
This PR depends on an external OAuth2 provider to provide and sign the tokens. For example, [Keycloak](https://www.keycloak.org/).
- `[buddy/buddy-core "1.6.0"]` for preparing the public key used to verify the token
- `[buddy/buddy-auth "2.2.0"]` for the provided ring middleware
To authenticate the clinical end-user (often, but not always, the patient), [FHIR specifies](http://www.hl7.org/fhir/smart-app-launch/scopes-and-launch-context/index.html#scopes-for-requesting-identity-data) that [OpenID …
=> Authentication

Dockerfile, README.md, docker-compose.yml
Modifies the Dockerfile to run the container as a non-root user instead of the default root. 
It also changes the runtime image to a Java distroless one, see https://github.com/GoogleContainerTools/distroless. These images are incredibly stripped down and, while sometimes annoying to work with, provide a significant security advantage over images which include shells and tools like wget/curl which may be used by an attacker. Additionally, this reduces the image size from ~430 MB to ~268MB uncompressed.
=> Run container as non-root user in a distroless image

modules/fhir-client/src/blaze/fhir_client.clj, modules/fhir-client/test/blaze/fhir_client_test.clj
These changes target issue #228 and implement basic authentication into the FHIR client.
The credentials are set while building the HttpClient and used for all requests requiring authentication. To change the credentials a new client needs to be created.
This feature can be useful, e.g. when accessing an IBM FHIR server in default configuration with authentication being enabled.
=> Add Basic Authentication to FHIR Client

modules/db/src/blaze/db/impl/index/resource_handle.clj, modules/fhir-structure/src/blaze/fhir/hash.clj, modules/fhir-structure/src/blaze/fhir/spec.clj, modules/fhir-structure/src/blaze/fhir/spec/impl.clj, modules/fhir-structure/src/blaze/fhir/spec/spec.clj, modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/src/blaze/fhir/spec/type/protocols.clj, modules/fhir-structure/test/blaze/fhir/spec/impl_test.clj, modules/fhir-structure/test/blaze/fhir/spec/type_test.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj
Moving the protocol into its own namespace that the advantage, that the
type namespace can be reloaded without reloading the protocol.
=> Move FhirType Protocol into its own Namespace

modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/node/resource_indexer_test.clj, modules/db/test/blaze/db/node/transaction_test.clj, modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/test/blaze/fhir/spec/type_test.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj
Hashing a typical Observations shows a 10% runtime speedup. On top of
that, fewer garbage is produced because instead of a new map, only a new
list of keys is produced.
=> Improve Hashing Performance

modules/module-base/deps.edn, modules/thread-pool-executor-collector/src/blaze/thread_pool_executor_collector.clj, src/blaze/system.clj
With help of the new `ref-resolve` protocol method, I'm able to
implement the RefMap directly in Blaze.
=> Move Back to Upstream Integrant Dependency

deps.edn, modules/db/src/blaze/db/impl/db.clj, perf-test/read-tests.sh, profiling/blaze/profiling.clj
Single calls to Db -resource-handle do not open a whole batch-db anymore. Instead the snapshot and ResourceAsOf iterator are opened separately.
=> Improve Performance of Resource Handle Function

modules/interaction/src/blaze/interaction/search_compartment.clj, modules/interaction/src/blaze/interaction/search_system.clj, modules/interaction/src/blaze/interaction/search_type.clj
By using take, bundle entries are a list. By switching to a vector, unforming will be faster. Also subvec is a lot faster, because it doesn't create a new list.
=> Bundle Entries of a Page Should be a Vector

integration-test/arithmetic/query.cql, integration-test/query-3/query.cql, integration-test/query-5/query.cql, integration-test/query-6/query.cql, integration-test/query-7/query.cql, integration-test/readme-example/query.cql, modules/cql/src/blaze/elm/compiler/external_data.clj, modules/cql/src/blaze/elm/compiler/reusing_logic.clj, modules/cql/test/blaze/elm/compiler/external_data_test.clj, modules/cql/test/blaze/elm/compiler/queries_test.clj, modules/cql/test/blaze/elm/compiler/structured_values_test.clj, modules/cql/test/blaze/elm/type_infer_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q34-medication-data.json, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q34-medication-query.cql
The new name for the context operating on the whole database is called
Unfiltered.
Closes #317
=> Rename CQL Context Unspecified into Unfiltered

modules/db/src/blaze/db/tx_log/local.clj, modules/db/test/blaze/db/tx_log/local_test.clj
I extended the JSONable protocol of cheshire at two places, once in
blaze.db.tx-log.local and once in blaze.fhir.spec.type. In
blaze.db.tx-log.local, I generated a number of the epoch seconds, were
in blaze.fhir.spec.type I called .toString.
I have decided to skip using JSONable in blaze.db.tx-log.local, because
there, I use an instant only once.
This case was not found by unit tests, because I do not load the
namespace blaze.db.tx-log.local in tests generating JSON from resources.
Instead it was detected by Touchstone.
=> Fix JSON Generation of Instant Values

modules/interaction/src/blaze/interaction/history/instance.clj, modules/interaction/src/blaze/interaction/history/system.clj, modules/interaction/src/blaze/interaction/history/type.clj, modules/interaction/src/blaze/interaction/search_compartment.clj, modules/interaction/src/blaze/interaction/search_system.clj, modules/interaction/src/blaze/interaction/search_type.clj, modules/interaction/src/blaze/interaction/transaction.clj, modules/module-base/src/blaze/uuid.clj
Random UUID's are expensive to create. LUID's are much faster. The lower
entropy of 36 bit is not a problem, because not more than one bundle
should be generated for each client per millisecond.
=> Use LUID's instead of Random UUID's

modules/interaction/test/blaze/interaction/create_test.clj, modules/interaction/test/blaze/interaction/delete_test.clj, modules/interaction/test/blaze/interaction/history/instance_test.clj, modules/interaction/test/blaze/interaction/history/system_test.clj, modules/interaction/test/blaze/interaction/history/type_test.clj, modules/interaction/test/blaze/interaction/history/util_test.clj, modules/interaction/test/blaze/interaction/read_test.clj, modules/interaction/test/blaze/interaction/search_compartment_test.clj, modules/interaction/test/blaze/interaction/search_system_test.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/interaction/test/blaze/interaction/transaction_test.clj, modules/interaction/test/blaze/interaction/update_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/handler/impl_test.clj, modules/rest-util/src/blaze/handler/fhir/util.clj, modules/rest-util/test/blaze/fhir/response/create_test.clj, modules/rest-util/test/blaze/handler/fhir/util_test.clj
I used reitit to generate the type, instance and versioned instance URL.
However reitit is very slow at encoding path parameters. because FHIR
ID's and our VID's are already URL safe, encoding isn't necessary. Also
the URL schema is fixed, so a decided to simply create them by hand. We
could revert to the old model if
https://github.com/metosin/reitit/issues/477 is solved.
=> Create Instance and Versioned URLs by Hand

dev/blaze/dev.clj, modules/db-stub/src/blaze/db/api_stub.clj, modules/db/src/blaze/db/impl/index/tx_success.clj, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/resource_handle_cache.clj, modules/db/src/blaze/db/resource_handle_cache/spec.clj, modules/db/src/blaze/db/spec.clj, modules/db/src/blaze/db/tx_cache.clj, modules/db/src/blaze/db/tx_cache/spec.clj, modules/db/test-perf/blaze/db/api_test_perf.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/impl/index/tx_success_spec.clj, modules/db/test/blaze/db/impl/index/tx_success_test.clj, modules/db/test/blaze/db/node/tx_indexer/verify_test.clj, modules/db/test/blaze/db/node_spec.clj, modules/db/test/blaze/db/node_test.clj, modules/db/test/blaze/db/resource_cache_test.clj, modules/db/test/blaze/db/resource_handle_cache_test.clj, modules/db/test/blaze/db/test_util.clj, modules/db/test/blaze/db/tx_cache_test.clj, profiling/blaze/profiling.clj, resources/blaze.edn
The transaction cache holds transaction data that currently only
consists of the instant at which the transaction happened. Transaction
data is keyed by t.
=> Implement a Transaction Cache

modules/db-resource-store-cassandra/src/blaze/db/resource_store/cassandra.clj, modules/db-resource-store-cassandra/test/blaze/db/resource_store/cassandra_test.clj
At the migration of the hash from Guava HashCode to byte strings in #271, I forgot to use bs/hex instead of str to create a hexadecimal representation of the hashes.
=> Fix Cassandra Key Serialization

.dockerignore, .github/workflows/build.yml, .gitignore, Dockerfile, Makefile
In the Docker build container, artefacts can't be cached. So building outside will be faster.
=> Move Build Out of Docker Build Container

.github/containerscan/allowedlist.yaml, Dockerfile
The Google [Distroless Java Project][1] is no longer maintained properly
to an extend that even Googles own [Jib Project][2] [moved][3] to
AdoptOpenJDK. So we will too.
[1]: <https://github.com/GoogleContainerTools/distroless>
[2]: <https://github.com/GoogleContainerTools/jib>
[3]: <https://github.com/GoogleContainerTools/jib/blob/master/docs/default_base_image.md#migration-from-pre-30>
=> Migrate to AdoptOpenJDK

.github/distributed-test/docker-compose.yml, .github/openid-auth-test/docker-compose.yml, .github/workflows/build.yml, CHANGELOG.md
I used to only build the GitHub Container Registry images tagged with the SHA and retag/push the Docker Hub Images myself. But now with the multi-arch build, that doesn't work anymore. Also is better to have everything in CI.
=> Build Docker Hub Images in CI

modules/rocksdb/src/blaze/db/kv/rocksdb.clj
Previously, I had the stats dumped to often, resulting in a too large LOG file. After that, I disabled the stats completely, but it's a good thing to have the stats at all.
=> Revert to Default Stats Dump Period of 10 Minutes

.github/containerscan/allowedlist.yaml, .github/workflows/build.yml, Dockerfile
The root cause to migrate was CVE-2021-3711 which isn't fixed in the latest AdoptOpenJDK projects but unfortunately also not in Eclipse Temurin. I opened adoptium/containers#43 and put CVE-2021-3711 on the allow-list.
https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/
https://adoptium.net
https://github.com/adoptium
=> Migrate to from AdoptOpenJDK Eclipse Temurin

modules/db/deps.edn, modules/db/src/blaze/db/impl/arrays_support.clj, modules/db/src/blaze/db/impl/iterators.clj, modules/db/test/blaze/db/impl/arrays_support_test.clj, modules/db/test/blaze/db/impl/iterators_test.clj
In case buffers are too small, they will be resized. But we did only
double the size without taking into account the actual required amount
to resize.
We used the same algorithm as in jdk.internal.util.ArraysSupport/newLength.
=> Fix Resizing of Buffers at Read

dev/blaze/dev/db.clj, modules/db-tx-log-kafka/src/blaze/db/tx_log/kafka.clj, modules/db-tx-log-kafka/test/blaze/db/tx_log/kafka_test.clj, modules/db-tx-log/src/blaze/db/tx_log.clj, modules/db-tx-log/src/blaze/db/tx_log_spec.clj, modules/db-tx-log/test/blaze/db/tx_log_test.clj, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/node/resource_indexer.clj, modules/db/src/blaze/db/tx_log/local.clj, modules/db/test/blaze/db/node/resource_indexer_spec.clj, modules/db/test/blaze/db/node/resource_indexer_test.clj, modules/db/test/blaze/db/tx_log/local_test.clj, modules/kv/src/blaze/db/kv/mem.clj, modules/kv/test/blaze/db/kv/mem_test.clj
The node had a transaction resource cache that stores resources of a
transaction by t. The node puts the resources after the transaction was
submitted successfully. However sometimes the node gets back the tx-data
from the transaction log before it puts the resources in the cache.
I removed this cache completely and send the resources as local payload
through the local transaction log. The Kafka transaction log on the
other hand doesn't transfer the resources.
=> Fix Memory Leak in Node

modules/db/src/blaze/db/tx_log/local/codec.clj, modules/db/test/blaze/db/tx_log/local_test.clj
Introduced in #469 we have no longer hashed in the delete command.
However, in the local transaction log implementation, we still try to
decode the hash. This fix has to be merged into the 0.12.0 release
branch.
=> Fix Decoding of Delete Command

.github/scripts/evaluate-measure-subject-list.sh, .github/workflows/build.yml, docs/cql-queries/api.md, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/middleware/params.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/middleware/params_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj, modules/rest-api/src/blaze/rest_api/routes.clj, modules/rest-api/test/blaze/rest_api/routes_test.clj, modules/rest-api/test/blaze/rest_api_test.clj
At POST the Parameters resource is used instead of URL-encoded params.
=> Fix Encoding of Parameters at Operation POST Requests

Dockerfile
Eclipse Temurin is currently slow to release new versions.
=> Move to OpenJDK

DEVELOPMENT.md, modules/db-resource-store-cassandra/src/blaze/db/resource_store/cassandra.clj, modules/db-tx-log-kafka/src/blaze/db/tx_log/kafka.clj, modules/db-tx-log-kafka/test/blaze/db/tx_log/kafka_test.clj, modules/db-tx-log/src/blaze/db/tx_log.clj, modules/db-tx-log/test/blaze/db/tx_log_test.clj, modules/db/src/blaze/db/api.clj, modules/db/src/blaze/db/impl/batch_db.clj, modules/db/src/blaze/db/impl/index/system_stats.clj, modules/db/src/blaze/db/impl/index/type_stats.clj, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/tx_log/local.clj, modules/db/test/blaze/db/tx_log/local_test.clj, modules/kv/src/blaze/db/kv.clj, modules/kv/src/blaze/db/kv/mem.clj, modules/kv/src/blaze/db/kv/spec.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj, modules/page-store-cassandra/src/blaze/page_store/cassandra.clj, src/blaze/server.clj, src/blaze/server_spec.clj
AutoCloseable is an interface introduced in Java 1.7 for the try-with-resources statement which is comparable with the with-open macro in Clojure. To be onest, both interfaces work for Clojure, but I think AutoCloseable is a bit more suitable because it has nothing to do with I/O.
=> Migrate from Closeable to AutoCloseable

.github/workflows/build.yml, Dockerfile
Today, Trivy detected 11 Critical Issues (UNKNOWN: 0, LOW: 11, MEDIUM: 25, HIGH: 9, CRITICAL: 11) in openjdk:17 which is based on oraclelinux:8.4.
However, openjdk:17-slim has only 2 Critical Issues (UNKNOWN: 0, LOW: 56, MEDIUM: 2, HIGH: 2, CRITICAL: 2). So we'll switch to Debian.
I also moved to the plain Trivy Action.
=> Migrate from Oracle Linux to Debian

modules/terminology-service/deps.edn, modules/terminology-service/src/blaze/terminology_service_spec.clj
The expand-value-set function returns a CompletableFuture instead of a Manifold deferred for some time now. This was just an oversight.
=> Remove Manifold from Terminology Service Module

Dockerfile
Go Back to Oracle Linux as Base Image
According to Trivy, Oracle Linux 8.5 has no vulnerabilities. I opened a question https://github.com/aquasecurity/trivy/discussions/1403.
=> Update Docker Base-Image

modules/cassandra/deps.edn
Added direct dependency to io.netty/netty-handler with current version.
=> Fix CVE-2021-37137 in Package io.netty:netty-codec

modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj
The resource handles do not have a :fhir/type key. We have to call type/type on them instead.
=> Fix Error Message in Operation $evaluate-measure

src/blaze/system.clj
I was trying to save memory for the metrics server what isn't really used much. But Jetty needs some minimum number of threads. This number depends on the number of cores. With a system of 16 cores, 4 threads are not sufficient.
More: https://github.com/eclipse/jetty.project/issues/2503
=> Fix Insufficient Configured Threads for the Metrics Server

modules/db/src/blaze/db/api_spec.clj, modules/db/src/blaze/db/node.clj, modules/db/test/blaze/db/api_test.clj, modules/interaction/src/blaze/interaction/search_type.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/interaction/test/blaze/interaction/transaction_test.clj
In the default lenient handling, invalid search values were ignored. This is not the intended behaviour. Only unknown search parameters should be ignored, but not invalid values.
=> Ensure Error Response on Invalid Value in FHIR Search

docs/deployment/environment-variables.md, modules/rest-api/src/blaze/rest_api.clj, modules/rest-api/src/blaze/rest_api/routes.clj, modules/rest-api/src/blaze/rest_api/spec.clj, modules/rest-api/test/blaze/rest_api_test.clj, modules/rest-util/src/blaze/middleware/fhir/db.clj, modules/rest-util/src/blaze/middleware/fhir/db_spec.clj, modules/rest-util/test/blaze/middleware/fhir/db_test.clj, src/blaze/system.clj
All reading FHIR interactions have to acquire the last database state known at the time the request arrived in order to ensure consistency. That database state might not be ready immediately because indexing might be still undergoing. In such a situation, the request has to wait for the database state becoming available. If the database state won't be available before the timeout expires, a 503 Service Unavailable response will be returned. Please increase this timeout if you experience such 503 responses, and you are not able to improve indexing performance or lower transaction load.
=> Allow Setting the Database Sync Timeout

.github/workflows/build.yml, modules/cassandra/deps.edn, modules/cassandra/src/blaze/cassandra.clj, modules/cassandra/src/blaze/cassandra/config.clj, modules/cassandra/src/blaze/cassandra/session.clj, modules/cassandra/src/blaze/cassandra_spec.clj, modules/cassandra/test/blaze/cassandra/config_test.clj, modules/cassandra/test/blaze/cassandra/session_spec.clj, modules/cassandra/test/blaze/cassandra/session_test.clj, modules/cassandra/test/blaze/cassandra_test.clj, modules/db-resource-store-cassandra/src/blaze/db/resource_store/cassandra.clj, modules/db-resource-store-cassandra/test/blaze/db/resource_store/cassandra_test.clj, modules/page-store-cassandra/src/blaze/page_store/cassandra.clj, modules/page-store-cassandra/test/blaze/page_store/cassandra_test.clj
Because we can execute the test coverage only sequentially, it is more efficient to do this in a single job rather than on multiple.
Also improved cassandra module test coverage in order to not lower the overall test coverage because the cassandra module was missing from the current job listing.
=> Improve Test Coverage Execution

Dockerfile
That should solve CVE-2021-3712 currently in Oracle Linux 8.5 and possibly many other vulnerabilities in the future.
=> Upgrade Oracle Linux Packages

modules/cassandra/deps.edn
The `com.esri.geometry/esri-geometry-api` v1.2.1 dependency is optional which is itself outdated and introduces other outdated dependencies. That dependencies are:
* `org.json/json` v20090211
* `org.codehaus.jackson/jackson-core-asl` v1.9.12
=> Exclude Geometry API from Java-Driver-Core

modules/byte-string/deps.edn
=> Update Google Protobuf to v3.19.2

.github/scripts/wait-for-url.sh, .github/workflows/build.yml
Use curl to wait for Blaze being available instead of just sleeping a long time. Removed the concurrency 4 part of the small transactions test because it is not really necessary.
=> Speed Up Integration Tests

modules/cql/src/blaze/elm/decimal.clj, modules/cql/src/blaze/elm/integer.clj, modules/cql/src/blaze/elm/quantity.clj
The number narrowing of the default number system is unnecessary and costly.
=> Improve CQL Quantity Creation

modules/cql/src/blaze/elm/compiler/logical_operators.clj, modules/cql/src/blaze/elm/compiler/macros.clj, modules/db/deps.edn, modules/fhir-path/src/blaze/fhir_path.clj
I saw this problem by starting Blaze with the YourKit profiler. The problem was always Clojure case expressions resulting in large Java switch statements.
=> Resolve Issues with Large Methods

modules/db/test/blaze/db/api_test.clj, modules/fhir-structure/resources/data_readers.clj, modules/fhir-structure/src/blaze/fhir/spec/impl.clj, modules/fhir-structure/src/blaze/fhir/spec/impl/intern.clj, modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/test/blaze/fhir/spec/impl/intern_test.clj, modules/fhir-structure/test/blaze/fhir/spec/impl_test.clj, modules/interaction/src/blaze/interaction/history/instance.clj, modules/interaction/src/blaze/interaction/history/system.clj, modules/interaction/src/blaze/interaction/history/type.clj, modules/interaction/src/blaze/interaction/history/util.clj, modules/interaction/src/blaze/interaction/search/util.clj, modules/interaction/src/blaze/interaction/search_compartment.clj, modules/interaction/src/blaze/interaction/search_system.clj, modules/interaction/src/blaze/interaction/search_type.clj, modules/interaction/src/blaze/interaction/transaction.clj, modules/interaction/test/blaze/interaction/transaction_test.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/stratifier.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/middleware/params.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj, modules/rest-api/src/blaze/rest_api/capabilities.clj, modules/rest-api/src/blaze/rest_api/middleware/auth_guard.clj, modules/rest-util/src/blaze/handler/util.clj
In FHIR, some values repeat in many resources. First uri's are used as system's in Codings and Identifiers. Second canonical values are used to refer to other resources. Third codes are often the same for a large number of resources. Last, Coding and CodeableConcept contain system and code values and are also often the same in it's entirety.
By interning instances of those values, only one instance will resist in memory as opposed to many. Because all values are immutable, there is no risk in sharing instances. The memory savings are about 50 % for Synthea BMI Observations.
=> Intern Uri, Canonical, Code, Coding and CodeableConcept

modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q38-di-surv-query.cql
Both are synonyms but during fits better in the date/time space.
=> Replace included in with during

evaluate-measure.sh
This is a problem in WSL. Jq outputs stuff with C println which outputs CRLF instead of LF under Windows.
=> Remove ^M grom the IDs extracted by jq -r

.github/workflows/build.yml
The version 2 is more common as the special codeql-bundle-20220401.
=> Change Version of CodeQL Upload Sarif to v2

modules/rest-api/src/blaze/rest_api.clj, modules/rest-api/src/blaze/rest_api/middleware/output.clj, modules/rest-api/test/blaze/rest_api_test.clj, modules/rest-util/src/blaze/handler/util.clj, modules/rest-util/test/blaze/handler/util_test.clj, test/blaze/system_test.clj
This problem was introduced in v0.17.1. Versions of Blaze before v0.17.1 are not effected.
HTTP Error Outputs with status codes 404 and 405 were not encoded to either JSON or XML, leading to an error in Jersey, leading to a 500.
This commit also introduces redirecting requests including a leading slash to ones without one.
=> Fix Server Errors Because of Unencoded Error Outputs

modules/rest-api/src/blaze/rest_api/middleware/output.clj, modules/rest-api/test/blaze/rest_api/middleware/output_test.clj
This fixes a regression introduced by #703 where we don't return JSON by default if an Accept header is present. This is relevant in situations where browsers start with text/html but also will accept application/xml with lower priority. Instead of returning a 406 in this cases, XML is delivered now.
If one prefers JSON in browsers the _format query param has to be used.
=> Fix Content Negotiation

modules/fhir-structure/src/blaze/fhir/spec/impl.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj
I like to have the constructor conformer last, because otherwise the record will be updated, which might be slower than updating a map.
Also added some tests regarding conforming extensions.
=> Reorder XML Conformer Steps

docs/performance/fhir-search.md, modules/db-resource-store/test/blaze/db/resource_store/cbor_test.clj, modules/db-stub/src/blaze/db/api_stub.clj, modules/db/test-perf/blaze/db/api_test_perf.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/impl/search_param/quantity_test.clj, modules/fhir-structure/resources/data_readers.clj, modules/fhir-structure/src/blaze/fhir/spec.clj, modules/fhir-structure/src/blaze/fhir/spec/impl.clj, modules/fhir-structure/src/blaze/fhir/spec/impl/specs.clj, modules/fhir-structure/src/blaze/fhir/spec/impl/util.clj, modules/fhir-structure/src/blaze/fhir/spec/impl/xml.clj, modules/fhir-structure/src/blaze/fhir/spec/impl_spec.clj, modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/src/blaze/fhir/spec/type/json.clj, modules/fhir-structure/src/blaze/fhir/spec/type/macros.clj, modules/fhir-structure/src/blaze/fhir/spec/type/protocols.clj, modules/fhir-structure/test-perf/blaze/fhir/spec/type_test_mem.clj, modules/fhir-structure/test-perf/blaze/fhir/spec_test_perf.clj, modules/fhir-structure/test/blaze/fhir/spec/generators.clj, modules/fhir-structure/test/blaze/fhir/spec/impl/xml_spec.clj, modules/fhir-structure/test/blaze/fhir/spec/impl_test.clj, modules/fhir-structure/test/blaze/fhir/spec/type/json_test.clj, modules/fhir-structure/test/blaze/fhir/spec/type_test.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/stratifier.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
All explicit modelled complex types will intern if they consist only of interned extensions. This will save memory for complex types tagged with a data absent reason extension.
Also some optimizations regarding encoding of resources as JSON were done in order to preserve encoding times reached before implementing extended primitive types.
=> Improve Interning of Complex Types

modules/cql/Makefile
Please revert it by closing: #734
=> Download CQL Tests using HTTP because the Certificate is Invalid

docs/database/migration.md, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/node/version.clj, modules/db/test/blaze/db/node_test.clj, modules/rest-util/src/blaze/middleware/fhir/db.clj, modules/rest-util/test/blaze/middleware/fhir/db_test.clj, modules/test-util/src/blaze/test_util.clj
Later features will be able to specify database version which is incompatible with older versions, detecting and requiring a database migration.
=> Introduce Database Versioning

modules/db-resource-store/src/blaze/db/resource_store/spec.clj, modules/db/src/blaze/db/impl/codec.clj, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/node/version.clj, modules/db/src/blaze/db/search_param_registry/spec.clj, modules/db/src/blaze/db/spec.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/impl/codec_test.clj, modules/db/test/blaze/db/impl/search_param/composite_test.clj, modules/db/test/blaze/db/node/resource_indexer_test.clj, modules/db/test/blaze/db/node/version_spec.clj, modules/db/test/blaze/db/node_test.clj, modules/db/test/blaze/db/resource_cache_test.clj
In case we have 1 million different identifiers, we will have v-hash collisions. So we have to increase the v-hash size from 32 bit to 64 bit.
=> Increase V-Hash Size from 32 Bit to 64 Bit

modules/db/test/blaze/db/node/transaction_test.clj, modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/test/blaze/fhir/spec/type_test.clj
This bug was introduced by #722. Reference resolution only works on non-extended Reference.reference string types. On extended string types however the value of the extended string has to be obtained by calling the value function. which also works on non-extended strings.
Closes: #758
=> Fix Reference Resolution on Extended Primitive References

.github/scripts/evaluate-measure-subject-list.sh, docs/cql-queries/api.md, evaluate-measure.sh, modules/fhir-structure/src/blaze/fhir/spec/impl.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/middleware/params_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
The example is a Task resource were the output value is given as with the bare "value" key instead of one of the concrete keys like "valueReference". Such properties can't be assigned a type and have to be removed.
=> Remove Bare Polymorph JSON Properties

Dockerfile, docs/deployment/manual-deployment.md, modules/server/deps.edn
The former used image openjdk:17-oracle is now 3 month old while the new image eclipse-temurin:17 is only 1 day old.
=> Migrate to Eclipse Temurin because OpenJDK is Deprecated

.github/distributed-test/docker-compose.yml, .github/openid-auth-test/docker-compose.yml, .github/workflows/build.yml
The variable github.sha points now to the merge commit of a PR but the Docker metadata action uses the SHA of the commit to merge.
I now build only a local Docker image and upload it to the artifact storage to be able to use it at the integration tests. The push to the registries will be done after all integration tests which has the advantage that a failing image will not be published.
=> [WIP] Fix Git SHA Problems in GitHub Actions

.github/test-data/bundle-with-references/bundle.json, .github/workflows/build.yml, modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/test/blaze/fhir/spec/generators.clj, modules/fhir-structure/test/blaze/fhir/spec/type_test.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj, modules/interaction/test/blaze/interaction/create_test.clj
Before, references inside Bundles were tried to resolve during transactions. That required resources to exists that were referenced inside Bundles. But Bundles should be stored "as-is", opaque without resolving any references in them.
This fix, changes the function blaze.fhir.spec.type/references to not look inside Bundle entries. The integration test
"bundle-with-references-test" was added to try to issue a transaction that stores a transaction bundle with a reference in it.
=> Fix Storage of Bundles with References

Dockerfile
Docker health check will need curl. However I don't introduce the actual health check in this PR because I don't oversee all implications. For now we have one user that will put the health check in the Docker Compose file.
=> Revert Purging curl for Future Docker Health Checks

.github/workflows/build.yml
The Test Coverage job doesn't require a minimal test coverage. Instead it just upload the coverage results and Codecov will comment later in the PR. We can create the Docker image of all tests run successfully, irrespective of the coverage analysis.
=> Remove Test Coverage Dependency from Push Image Job

.github/scripts/evaluate-measure-timeout.sh, .github/workflows/build.yml, docs/cql-queries.md, docs/deployment/environment-variables.md, docs/performance/fhir-search/simple-code-search.sh, docs/performance/import.sh, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql/spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/population/spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/population_spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier/spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj, resources/blaze.edn
The environment variable FHIR_OPERATION_EVALUATE_MEASURE_TIMEOUT can be used to set a evaluate measure timeout in milliseconds. The default value will be 1 hour in order to prevent overly long evaluations from slowing down Blaze. At the same time the default should not change the behaviour of normal evaluations.
=> Add Evaluate Measure Timeout

modules/db-stub/src/blaze/db/api_stub.clj, modules/db/src/blaze/db/impl/batch_db.clj, modules/db/src/blaze/db/impl/search_param/all.clj, modules/db/src/blaze/db/impl/search_param/date.clj, modules/db/src/blaze/db/impl/search_param/quantity.clj, modules/db/src/blaze/db/impl/search_param/util.clj, modules/db/src/blaze/db/node.clj, modules/db/test-perf/blaze/db/api_test_perf.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/test_util.clj, modules/db/test/blaze/db/tx_log/local_test.clj, modules/fhir-structure/src/blaze/fhir/hash.clj, modules/interaction/test/blaze/interaction/create_test.clj, modules/interaction/test/blaze/interaction/history/instance_test.clj, modules/interaction/test/blaze/interaction/history/system_test.clj, modules/interaction/test/blaze/interaction/history/type_test.clj, modules/interaction/test/blaze/interaction/search_compartment_test.clj, modules/interaction/test/blaze/interaction/search_system_test.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/interaction/test/blaze/interaction/transaction_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj, modules/test-util/src/blaze/test_util.clj, test/blaze/system_test.clj
Searching resources by _lastUpdated can return a resource more than once.
The problem with the meta.lastUpdated property is that it doesn't contribute to the content hash of a resource because it's not part of the resource content. This results in multiple entries into the SearchParamValueResource index having the same content hash. If that content hash is equal to the current one, the resource is returned multiple times.
The fix moves the _lastUpdated search clause away from the first position because the first clause uses the SearchParamValueResource index.
Closes: #882
=> Fix _lastUpdated Search Returning a Resource more than Once

.github/scripts/generate-large-binary-resource.sh, .github/workflows/build.yml, docker-compose.yml, modules/fhir-structure/deps.edn, modules/rest-api/src/blaze/rest_api/middleware/resource.clj, modules/rest-api/test/blaze/rest_api/middleware/resource_test.clj
The Woodstox XML Parser has a default limit of 524288 bytes for XML attribute values in order to prevent DOS attacks. However for FHIR Binary resources that limit is just to low. I decided against a configurable limit, because the possibility to do so is implementation specific to Woodstox and I can't guarantee that I can implement it using other libraries. So I disabled the limit completely.
=> Allow Writing Large Binary Resources in XML Format

modules/db/deps.edn, modules/db/src/blaze/db/impl/search_param/string.clj, modules/db/src/blaze/db/impl/search_param/util.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/impl/search_param/string_test.clj, modules/db/test/blaze/db/impl/search_param/util_spec.clj, modules/db/test/blaze/db/impl/search_param/util_test.clj
There was a bug in clj-fuzzy.phonetics/soundex crashing with a question mark as input. I switched to org.apache.commons.codec.language.Soundex ans added property-based tests testing 10.000 random strings.
I also skip indexing strings with chars that have no mapping. This decision might be changed later. For example words with German umlauts are not index at all now.
I also tested the old implementation against the new one with the alpha words from https://github.com/dwyl/english-words. Only about 10 words were different.
I also fixed phonetic search at all, because the search value was not normalized using the soudex algorithm. Only indexing was done using it. So before this commit the phonetic search did actually not work.
Closes: #903
=> Fix Indexing Error during Soundex Calculation

.github/scripts/authenticated-request.sh, .github/scripts/check-capability-statement.sh, .github/scripts/create-patient.sh, .github/scripts/not-acceptable.sh, .github/scripts/wait-for-url.sh, .github/workflows/build.yml, modules/interaction/src/blaze/interaction/history/util.clj, modules/interaction/test/blaze/interaction/create_test.clj, modules/interaction/test/blaze/interaction/history/instance_test.clj, modules/interaction/test/blaze/interaction/history/system_test.clj, modules/interaction/test/blaze/interaction/history/type_test.clj, modules/interaction/test/blaze/interaction/history/util_test.clj, modules/interaction/test/blaze/interaction/search_compartment_test.clj, modules/interaction/test/blaze/interaction/search_system_test.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/interaction/test/blaze/interaction/transaction_test.clj, modules/interaction/test/blaze/interaction/update_test.clj, modules/rest-util/src/blaze/handler/fhir/util.clj, modules/rest-util/test/blaze/handler/fhir/util_test.clj, modules/spec/src/blaze/spec.clj
In #925, I changed the implementation of blaze.handler.fhir.util/type-url, instance-url and versioned-instance-url so that I no longer payed attention to the context path. So URL's generated by that functions missed the context-path.
Also fixed the Bundle.entry.request.url in history bundles.
=> Fix URL Generation

modules/db/src/blaze/db/api_spec.clj, modules/db/src/blaze/db/impl/search_param/has.clj, modules/db/test/blaze/db/api_test.clj
It was possible to omit parts of the reverse chaining search parameter _has which resulted in a 500 because string splitting on nil. This fix reports the individual missing parts.
=> Improve Reverse Chaining Error Handling

docs/performance/cql.md, docs/performance/cql/code-value-search.sh, docs/performance/cql/observation-17861-6.yml, docs/performance/cql/observation-29463-7.yml, docs/performance/cql/observation-39156-5.yml, docs/performance/cql/observation-body-weight-10.yml, docs/performance/cql/observation-body-weight-100.yml, docs/performance/cql/observation-body-weight-50.yml, docs/performance/cql/observation-category-laboratory.cql, docs/performance/cql/observation-category-laboratory.yml, docs/performance/cql/observation-code-search.sh, modules/operation-measure-evaluate-measure/deps.edn, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/population.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/util.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql/spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/util_spec.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
Evaluating a Measure with reportType of population and no stratifier doesn't need collect the handles. This change determines that situation and just calculates the population count instead of collecting all handles.
This changes enables Blaze to determine the count of large populations were previously lots of memory was used for no reason.
=> Improve Performance Evaluating Measures without Stratifier

dev/blaze/dev.clj, modules/db/src/blaze/db/cache_collector.clj, modules/db/src/blaze/db/cache_collector/protocols.clj, modules/db/src/blaze/db/resource_cache.clj, modules/db/test/blaze/db/cache_collector_test.clj, modules/db/test/blaze/db/resource_cache_test.clj
The new metric is called `blaze_db_cache_estimated_size`.
=> Add Estimated Size to Cache Metrics

.github/scripts/transaction-null-resource.sh, .github/workflows/build.yml, modules/fhir-structure/src/blaze/fhir/spec.clj, modules/fhir-structure/src/blaze/fhir/spec/impl.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj, modules/rest-api/test/blaze/rest_api/middleware/resource_test.clj
The root cause was that if resources in bundles have no resourceType, the conversion from JSON/XML to the internal representation will fail with a NPE. Not an appropriate error is generated.
=> Fix Null Resource in Transactions Result in a 500

modules/interaction/src/blaze/interaction/search/util.clj
This should be reverted after it is clear why there are resources without a type.
=> Temporarily Support Bundle Entries with Typeless Resources

.github/workflows/build.yml
In order to prepare for the next Java LTS Version 21 in september, we start testing under Java 20.
=> Add Java 20 To Test Matrix

.github/scripts/check-total-number-of-resources.sh, .github/scripts/download-resources-query.sh, .github/workflows/build.yml, docs/performance/fhir-search.md, docs/performance/fhir-search/date-search.sh, modules/db/src/blaze/db/impl/index/search_param_value_resource.clj, modules/db/src/blaze/db/impl/search_param/date.clj, modules/db/test/blaze/db/api_test.clj
Used indexes for equal, less than and starts after. That operators all have a predicate on the lower bound of the resource value that comes first in the index. The other operators can't use the existing index, because they either look at the upper bound or on both bounds.
We have to add indexes in order to speed up the other operators. The issue is: #976.
=> Improve Date Search Performance

modules/db/test/blaze/db/api_test.clj, modules/fhir-structure/.clj-kondo/config.edn, modules/fhir-structure/src/blaze/fhir/spec.clj, modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/test/blaze/fhir/spec/type_test.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj, modules/test-util/.clj-kondo/config.edn, modules/test-util/src/blaze/fhir/spec/generators.clj
ExtendedInstant could not handle null values. I added transaction tests with a diagnostic report containing an issued instant.
=> Fix Extended Instant

modules/cql/test/blaze/elm/compiler/arithmetic_operators_test.clj
Adding Days to a Date already near the year 9999 can produce an overflow that will result in nil, so that the comparison will be also nil. Testing for not false will do the trick.
=> Fix CQL Test

modules/cql/src/blaze/elm/compiler/reusing_logic.clj, modules/cql/test/blaze/elm/compiler/reusing_logic_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q1.json, modules/page-store-cassandra/src/blaze/page_store/cassandra.clj
The CQL ToString function was not extracting the value out of a FHIR primitive value.
=> Fix CQL ToString Function

modules/db/Makefile, modules/db/build.clj, modules/db/deps.edn, modules/db/java/blaze/db/impl/index/resource_as_of/Key.java, modules/db/src/blaze/db/cache_collector.clj, modules/db/src/blaze/db/cache_collector/spec.clj, modules/db/src/blaze/db/impl/batch_db.clj, modules/db/src/blaze/db/impl/db.clj, modules/db/src/blaze/db/impl/index/resource_as_of.clj, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/resource_handle_cache.clj, modules/db/src/blaze/db/spec.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/cache_collector_test.clj, modules/db/test/blaze/db/impl/index/resource_as_of_spec.clj, modules/db/test/blaze/db/node_test.clj, modules/db/test/blaze/db/resource_handle_cache_test.clj
Before, if one sets the max-size of the resource handle cache to zero, a cache was still created which results in a certain overhead on each lookup. Now this overhead is eliminated because no cache is created and the lookup is performed directly into the RocksDB index.
=> Disable Resource Handle Cache if Max-Size Zero

.github/scripts/follow-next-link-after-write.sh, .github/workflows/build.yml, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/rest-util/src/blaze/handler/fhir/util_spec.clj, modules/rest-util/src/blaze/middleware/fhir/db.clj, modules/rest-util/test/blaze/middleware/fhir/db_test.clj
I was actually not using an as-of database for requests with a __t query param. So although the database was synced on t, as sync returns the newest database with at least t, we were operating on a to new database if writes happened in between. A simple as-of call to the database will do the trick to get a database with exactly t.
=> Fix Non-Stable Paging

.github/scripts/follow-patient-next-link-after-write.sh, .github/scripts/follow-system-next-link-after-write.sh, .github/scripts/read-ignores-t.sh, .github/workflows/build.yml, modules/anomaly/src/blaze/anomaly.clj, modules/anomaly/src/blaze/anomaly_spec.clj, modules/anomaly/test/blaze/anomaly_test.clj, modules/interaction/.clj-kondo/config.edn, modules/interaction/src/blaze/interaction/read.clj, modules/interaction/test/blaze/interaction/history/instance_test.clj, modules/interaction/test/blaze/interaction/history/system_test.clj, modules/interaction/test/blaze/interaction/history/type_test.clj, modules/interaction/test/blaze/interaction/read_test.clj, modules/interaction/test/blaze/interaction/search_compartment_test.clj, modules/interaction/test/blaze/interaction/search_system_test.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/interaction/test/blaze/interaction/transaction_test.clj, modules/operation-graphql/test/blaze/fhir/operation/graphql_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj, modules/rest-api/src/blaze/rest_api/routes.clj, modules/rest-api/test/blaze/rest_api_test.clj, modules/rest-util/src/blaze/middleware/fhir/db.clj, modules/rest-util/src/blaze/middleware/fhir/db_spec.clj, modules/rest-util/test/blaze/middleware/fhir/db_test.clj
Most requests should operate on the newest database state. So respecting the __t query param on all requests would expose an extensive API that we don't like to support. Now only the endpoints of paging and self links support the __t query param.
=> Ignore __t Query Param on Most Requests

docs/index.md
When clicking "View on GitHub" in documentation page, the repo opened is [vitepress](https://github.com/vuejs/vitepress) instead of [blaze](https://github.com/samply/blaze)
=> Update View On GitHub link in doc to Blaze repo

docs/monitoring/blaze.json, modules/metrics/src/blaze/metrics/core.clj, modules/metrics/src/blaze/metrics/core_spec.clj, modules/metrics/src/blaze/metrics/spec.clj, modules/rocksdb/src/blaze/db/kv/rocksdb.clj, modules/rocksdb/src/blaze/db/kv/rocksdb/metrics.clj, modules/rocksdb/test/blaze/db/kv/rocksdb/metrics_test.clj, modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj, resources/blaze.edn
The metrics are called `blaze_rocksdb_block_cache_usage_bytes` and `blaze_rocksdb_block_cache_pinned_usage_bytes`.
=> Add RocksDB Block Cache Usage Metrics

modules/db/test/blaze/db/api_test.clj
The runtime was about 10 to 20 minutes on GitHub Actions. So I decided to lower the number of generative tests run.
=> Make Module Database Tests Run Faster

Dockerfile
Using jemalloc solves memory fragmentation. I observed this problem while using block cache sizes above 1 GiB were RocksDB needed roughly 3 - 4 times the memory specified for the block cache.
See also: 
* http://smalldatum.blogspot.com/2018/04/myrocks-malloc-and-fragmentation-strong.html
* https://blog.cloudflare.com/the-effect-of-switching-to-tcmalloc-on-rocksdb-memory-use/
=> Use Jemalloc for RocksDB

modules/page-store/src/blaze/page_store/local.clj, modules/page-store/src/blaze/page_store/weigh.clj, modules/page-store/test/blaze/page_store/weigh_test.clj
I did not take into account that the PersistentVector/EMPTY_NODE is shared between vectors. So the size is a lot smaller.
=> Fix Weight Calculation in Page Store

modules/interaction/src/blaze/interaction/search_type.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/page-store/src/blaze/page_store/local.clj, modules/page-store/src/blaze/page_store/spec.clj, modules/page-store/test/blaze/page_store/local_test.clj, resources/blaze.edn, test/blaze/system_test.clj
We have also included the metric "blaze_page_store_estimated_size" to enable monitoring of the size. Additionally, we have decided to avoid generating tokens for searches that yield zero matches because such searches are fast and can result in a large number of useless tokens.
=> Increase Local Page Store Size

modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/test/blaze/fhir/spec/type_test.clj
Normally the XHTML data type must contain a valid XHTML &lt;div> element including the namespace. But we don't enforce that. This fix will wrap invalid XHTML content into such a &lt;div> element.
=> Fix Output of Invalid XHTML into XML

.github/custom-search-parameters-test/create-patient.sh, .github/custom-search-parameters-test/custom-search-parameters.json, .github/custom-search-parameters-test/docker-compose.yml, .github/custom-search-parameters-test/search-patient.sh, .github/workflows/build.yml, docs/deployment/custom-search-parameters.json, docs/deployment/docker-deployment.md, docs/deployment/environment-variables.md, modules/db-protocols/src/blaze/db/impl/protocols.clj, modules/db/.clj-kondo/config.edn, modules/db/src/blaze/db/search_param_registry.clj, modules/db/src/blaze/db/search_param_registry/spec.clj, modules/db/test/blaze/db/search_param_registry_test.clj, resources/blaze.edn
Using the environment variable `DB_SEARCH_PARAM_BUNDLE` it's possible to specify a bundle of custom search parameters which are used to index resources and made available via FHIR search.
=> Add Support for Custom Search Parameters

modules/cql/.clj-kondo/config.edn, modules/cql/src/blaze/elm/compiler/string_operators.clj, modules/cql/test/blaze/cql_translator_test.clj, modules/cql/test/blaze/elm/compiler/aggregate_operators_test.clj, modules/cql/test/blaze/elm/compiler/comparison_operators_test.clj, modules/cql/test/blaze/elm/compiler/string_operators_test.clj, modules/db-resource-store-cassandra/.clj-kondo/config.edn, modules/db-resource-store/.clj-kondo/config.edn, modules/db/.clj-kondo/config.edn, modules/interaction/.clj-kondo/config.edn, modules/operation-graphql/.clj-kondo/config.edn, modules/operation-measure-evaluate-measure/.clj-kondo/config.edn, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q49-length.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q49-length.json, modules/rest-util/.clj-kondo/config.edn
The CQL Length function returned an integer instead of a long. However the comparison operators work only with longs. I fixed that by ensuring that Length returns a long.
=> Fix Comparison of Length Result not Possible in CQL

.github/workflows/build.yml, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
I forgot to carry over the LUID's from Measure group to group.
=> Fix Evaluate Measure Generating Duplicate List IDs

Dockerfile
We used a shell in the docker entrypoint in order to be able to specify the absolute path to libjemalloc.so.2. However that isn't necessary as documented in https://man7.org/linux/man-pages/man8/ld.so.8.html. So we switch back to a direct java -jar call in the entrypoint.
Note that this will not change the runtime behaviour of Blaze because in the shell, we used exec to break out of the shell and have the java process running as the only process in the container.
Closes: #1034
=> Remove Shell in Docker Entrypoint

modules/cassandra/deps.edn
This vulnerability isn't relevant for Blaze because we use Netty only for client connections to Cassandra. The risk that Cassandra would work as an attack vector for DOS attacks agains Blaze is considered very low.
So this security fix doesn't demand an immediate release of a security fix version of Blaze. Also not marked as `security` for that reason.
=> Update Netty to Resolve CVE-2023-34462

modules/operation-graphql/deps.edn
I had replaced the ordered-map in Lacinia with array-map because of performance reasons. Having the official dependency is currently more important than improved performance.
=> Revert to Official Lacinia Dependency

.github/workflows/build.yml, modules/jepsen/Makefile
The distributed test takes currently up to 30 minutes. This is too long. I've provided a test which runs in fast succession (delta-time=0.01) and one that runs slower (delta-time=0.1) and so produces less output that has to be analyzed.
=> Improve Jepsen Test Runtime

modules/rest-util/deps.edn
I had accidentally used an alpha version here.
=> Revert Reitit Version to 0.6.0

.github/workflows/build.yml, modules/db-protocols/src/blaze/db/impl/protocols.clj, modules/db/src/blaze/db/impl/index.clj, modules/db/src/blaze/db/impl/search_param.clj, modules/db/src/blaze/db/impl/search_param/has.clj, modules/db/src/blaze/db/impl/search_param/token.clj, modules/db/test/blaze/db/api_test.clj
This issue solved the problem of using iterators concurrently by defensively open new ones for the `resource-handles` function in `blaze.db.impl.search-param.has`. This is more like a hot fix while the sustainable solution would be to resolve #1217.
Closes: #1215
=> Fix Empty Results in Certain Reverse Chaining FHIR Search Queries

modules/cql/.clj-kondo/config.edn, modules/cql/src/blaze/elm/quantity.clj, modules/db-resource-store-cassandra/.clj-kondo/config.edn, modules/db-resource-store-cassandra/test/blaze/db/resource_store/cassandra_test.clj, modules/db-resource-store/.clj-kondo/config.edn, modules/db-resource-store/test/blaze/db/resource_store/kv_test.clj, modules/db/test-perf/blaze/db/impl/index/resource_handle_test_perf.clj, modules/db/test/blaze/db/api_test.clj, modules/fhir-structure/deps.edn, modules/fhir-structure/src/blaze/fhir/spec/impl.clj, modules/fhir-structure/src/blaze/fhir/spec/type/macros.clj, modules/fhir-structure/src/blaze/fhir/spec/type/string_util.clj, modules/fhir-structure/test-perf/blaze/fhir/spec/type_test_mem.clj, modules/fhir-test-util/src/blaze/fhir/spec/generators.clj, modules/interaction/.clj-kondo/config.edn, modules/interaction/test/blaze/interaction/search/nav_test.clj, modules/interaction/test/blaze/interaction/search/params_test.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/page-store-cassandra/test/blaze/page_store/cassandra/codec_test.clj, modules/page-store-cassandra/test/blaze/page_store/cassandra_test.clj, modules/page-store/test/blaze/page_store/local_test.clj, modules/page-store/test/blaze/page_store/weigh_test.clj
We only used cuerdas for some basic string manipulation that is also possible with a combination of clojure/string and Guava CaseFormat.
Removing the cuerdas dependency will result in less maintenance work regarding updates, a smaller Docker image footprint and attack vector.
=> Remove funcool/cuerdas Dependency

.github/workflows/build.yml, .github/workflows/coverage.yml
Calculating the test coverage is independent from all other parts of the build workflow. It also takes the most of the time and so it would be good to have it run parallel to all other jobs. Putting it into its own Workflow also makes sense because we like to have it run only on PR's towards develop.
=> Move Test Coverage into its own Workflow

.github/scripts/patient-everything.sh, .github/scripts/patient-everything/X79746011X-type-counts.csv, modules/db/src/blaze/db/impl/batch_db.clj, modules/db/src/blaze/db/search_param_registry.clj, modules/db/src/blaze/db/search_param_registry_spec.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/search_param_registry_test.clj, modules/operation-patient-everything/test/blaze/operation/patient/everything_test.clj
The problem was that compartment definitions sometimes define more than one search parameter for resource type. For example the Patient compartments defines that MedicationAdministration is reachable via the search params patient, performer or subject. Especially the search param patient and subject points to the same Patient resource. By following each of the search params separately and just concatenating the results, we did output duplicate resources.
I did apply the function distinct for all resources of a given type in order top prevent the duplicates.
Closes: #1287
=> Fix Operation $everything return Duplicate Entries

docs/performance/import.md, modules/rocksdb/deps.edn, modules/rocksdb/src/blaze/db/kv/rocksdb/impl.clj, modules/rocksdb/src/blaze/db/kv/rocksdb/spec.clj, modules/rocksdb/test/blaze/db/kv/rocksdb/impl_test.clj, resources/blaze.edn
Don't set compaction_readahead_size to zero by default because the new default of RocksDB is non-zero.
=> Update dependency org.rocksdb/rocksdbjni to v8.8.1

modules/cql/src/blaze/elm/compiler/queries.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q52-sort-with-missing-values.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q52-sort-with-missing-values.json
The test q52-sort-with-missing-values shows that sorting in CQL works with missing values.
Also removed dead code in namespace blaze.elm.compiler.queries.
Related to: #1315
=> Show that Sorting Works with Missing Values

modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q53-population-basis-boolean.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q53-population-basis-boolean.json
The bug was introduced by #1335 in v0.23.3.
The problem was that I decided to change the value of the special boolean population basis from `:boolean` to `nil` but did it only half way.
Closes: #1397
=> Fix Error while Evaluating Measure with Population Basis Boolean

modules/db-resource-store/src/blaze/db/resource_store/kv.clj, modules/db-resource-store/test/blaze/db/resource_store/kv_test.clj, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/tx_log/local.clj, modules/db/src/blaze/db/tx_log/local/codec.clj, modules/db/test/blaze/db/impl/iterators_test.clj, modules/db/test/blaze/db/node_test.clj, modules/db/test/blaze/db/tx_log/local_test.clj, modules/interaction/test/blaze/interaction/transaction_test.clj, modules/interaction/test/blaze/interaction/update_test.clj, modules/kv/src/blaze/db/kv.clj, modules/kv/src/blaze/db/kv/mem.clj, modules/kv/src/blaze/db/kv/spec.clj, modules/kv/src/blaze/db/kv_spec.clj, modules/kv/test/blaze/db/kv/mem_test.clj, modules/rocksdb/src/blaze/db/kv/rocksdb.clj, modules/rocksdb/src/blaze/db/kv/rocksdb/impl.clj, modules/rocksdb/test/blaze/db/kv/rocksdb/impl_spec.clj, modules/rocksdb/test/blaze/db/kv/rocksdb/impl_test.clj, modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
RocksDB has a custom API for the default column family from the time before column family support. We used that custom api also in the Key Value Store abstraction, because we didn't know that it's the same as accessing the default column family.
This change simplifies the Key Value Store API.
=> Remove Custom API for Default Column Family

.clj-kondo/root/config.edn, docs/tuning-guide.md, modules/db-tx-log/src/blaze/db/tx_log/spec.clj, modules/db/src/blaze/db/impl/search_param.clj, modules/db/src/blaze/db/impl/search_param/token.clj, modules/db/src/blaze/db/impl/search_param/util.clj, modules/db/test/blaze/db/impl/index/resource_handle_spec.clj, modules/fhir-structure/src/blaze/fhir/spec/references.clj, modules/fhir-structure/src/blaze/fhir/spec/references_spec.clj, modules/fhir-structure/src/blaze/fhir/spec/spec.clj, modules/fhir-structure/src/blaze/fhir/spec/type_spec.clj, modules/fhir-structure/test/blaze/fhir/spec/references_test.clj, modules/fhir-structure/test/blaze/fhir/spec/spec_test.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj, modules/interaction/test/blaze/interaction/transaction/bundle/url_spec.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/spec.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/middleware/params.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
Before, we did just split the library reference by / and expected the second part to be the library id. Now we ensure that the library reference is a valid :blaze.fhir/literal-ref and that the resource type is Library.
=> Improve Finding of Library Resource by Literal Ref

modules/byte-buffer/src/blaze/byte_buffer.clj, modules/kv/src/blaze/db/kv.clj, modules/kv/src/blaze/db/kv_spec.clj, modules/kv/test/blaze/db/kv/mem_test.clj, modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
Since RocksDB v8.10.0 the byte buffers don't need to be direct anymore. This commit removes any notion of direct byte buffers from the key value store API.
=> Remove Direct Byte Buffer Usage

modules/db/src/blaze/db/impl/index/resource_search_param_value.clj, modules/db/src/blaze/db/impl/iterators.clj, modules/db/src/blaze/db/impl/search_param/composite/token_token.clj, modules/db/src/blaze/db/impl/search_param/string.clj, modules/db/src/blaze/db/impl/search_param/token.clj, modules/db/test/blaze/db/impl/index/resource_search_param_value_spec.clj, modules/db/test/blaze/db/impl/iterators_spec.clj, modules/db/test/blaze/db/impl/search_param/token_spec.clj
With the new function blaze.db.impl.iterators/contains-key-prefix? the seek into ResourceSearchParamValue index doesn't have the read the key back for token and string search.
=> Improve Secondary Search Clause Matching

modules/db/src/blaze/db/impl/index.clj, modules/db/test/blaze/db/api_test.clj
Before one filter xform was created that looped over the clauses, now a function composition of one filter per clause is created. The new xform will still short cut after the first non-match and has the advantage that the clauses do not have to be looped over in every filter step.
=> Improve other-clauses-filter Function

docs/performance/fhir-search.md, modules/db-protocols/src/blaze/db/impl/protocols.clj, modules/db/src/blaze/db/impl/index.clj, modules/db/src/blaze/db/impl/search_param.clj, modules/db/src/blaze/db/impl/search_param/all.clj, modules/db/src/blaze/db/impl/search_param/chained.clj, modules/db/src/blaze/db/impl/search_param/composite/token_quantity.clj, modules/db/src/blaze/db/impl/search_param/composite/token_token.clj, modules/db/src/blaze/db/impl/search_param/date.clj, modules/db/src/blaze/db/impl/search_param/has.clj, modules/db/src/blaze/db/impl/search_param/list.clj, modules/db/src/blaze/db/impl/search_param/number.clj, modules/db/src/blaze/db/impl/search_param/quantity.clj, modules/db/src/blaze/db/impl/search_param/string.clj, modules/db/src/blaze/db/impl/search_param/token.clj, modules/db/src/blaze/db/impl/search_param/util.clj, modules/db/test/blaze/db/impl/search_param_spec.clj
FHIR Search queries using `_summary=count` with a single search parameter are already fast. On a properly spaced system about 2 million resources can be counted per second.
However, if the FHIR search query contains more than one search parameter, the performance was about 10 times slower. 
With this PR, the performance will be on the same level as for queries with a single search parameter. This is achieved by parallelise also such queries.
=> Improve FHIR Search Count Performance

.github/scripts/check-referential-integrity-for-delete.sh, .github/scripts/delete.sh, .github/scripts/transactional-delete.sh, .github/workflows/build.yml, docs/api.md, modules/db-protocols/src/blaze/db/impl/protocols.clj, modules/db-tx-log/src/blaze/db/tx_log/spec.clj, modules/db-tx-log/test/blaze/db/tx_log/spec_test.clj, modules/db/src/blaze/db/api.clj, modules/db/src/blaze/db/api_spec.clj, modules/db/src/blaze/db/impl/batch_db.clj, modules/db/src/blaze/db/impl/db.clj, modules/db/src/blaze/db/impl/index/resource_handle.clj, modules/db/src/blaze/db/node/transaction.clj, modules/db/src/blaze/db/node/tx_indexer/verify.clj, modules/db/src/blaze/db/search_param_registry.clj, modules/db/src/blaze/db/search_param_registry_spec.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/impl/index/resource_handle_spec.clj, modules/db/test/blaze/db/impl/index/resource_handle_test.clj, modules/db/test/blaze/db/node/transaction_test.clj, modules/db/test/blaze/db/node/tx_indexer/verify_test.clj, modules/db/test/blaze/db/search_param_registry_test.clj, modules/rest-api/src/blaze/rest_api/capabilities.clj
=> Maintain Referential Integrity while Deleting Resources

.github/scripts/follow-patient-next-link-after-write.sh, .github/scripts/follow-system-next-link-after-write.sh, .github/scripts/forwarded-header.sh, .github/scripts/x-forwarded-headers.sh, codecov.yml, modules/interaction/src/blaze/interaction/search/nav.clj, modules/interaction/src/blaze/interaction/search_compartment.clj, modules/interaction/src/blaze/interaction/search_system.clj, modules/interaction/src/blaze/interaction/search_type.clj, modules/interaction/test/blaze/interaction/search/nav_spec.clj, modules/interaction/test/blaze/interaction/search/nav_test.clj, modules/interaction/test/blaze/interaction/search_compartment_test.clj, modules/interaction/test/blaze/interaction/search_system_test.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/rest-api/src/blaze/rest_api/routes.clj, modules/rest-api/test/blaze/rest_api_test.clj, modules/rest-util/src/blaze/middleware/fhir/db.clj, modules/rest-util/src/blaze/middleware/fhir/db_spec.clj, modules/rest-util/test/blaze/middleware/fhir/db_test.clj, test/blaze/system_test.clj
Self links should point to the location were a new FHIR search can be started and not to the immutable page of the current search result.
This also means that only the first page will contain a self link. Furthermore the Search Type and Search System endpoint will no longer need to obtain a database with a certain t. So databases with a certain t will only needed to be obtained by __page endpoints and vread. This makes the surface area of getting access to older database states smaller.
=> Remove Database T from Self Links

modules/cassandra/Makefile, modules/cassandra/deps.edn, modules/cql/deps.edn, modules/fhir-path/Makefile, modules/fhir-path/deps.edn, modules/operation-graphql/deps.edn, modules/rest-api/deps.edn
* removed spotbugs-annotations, findbugs/jsr305, javax.json and xpp3/xpp3 because it's not needed
* downgraded antlr4 to v4.10.1 because CQL is build with it
=> Optimize Dependencies

modules/fhir-structure/.clj-kondo/config.edn, modules/fhir-structure/src/blaze/fhir/spec/impl.clj, modules/fhir-structure/src/blaze/fhir/spec/type.clj, modules/fhir-structure/src/blaze/fhir/spec/type/system.clj, modules/fhir-structure/test/blaze/fhir/spec/impl_test.clj, modules/fhir-structure/test/blaze/fhir/spec/type/system_test.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj, modules/fhir-test-util/src/blaze/fhir/spec/generators.clj, modules/rest-api/src/blaze/rest_api/middleware/output.clj, modules/rest-api/test/blaze/rest_api/middleware/output_test.clj, modules/rest-api/test/blaze/rest_api/middleware/resource_test.clj
If resources contain control characters like \u001e (record separator) in strings or other string like primitive type values, the XML generator can't output them. Because the resulting exception is not handled, the output hangs and will never finish.
Closes: #1552
=> Fix XML Output for Resources with Control Chars

modules/admin-api/src/blaze/admin_api.clj, modules/kv/src/blaze/db/kv.clj, modules/kv/src/blaze/db/kv/mem.clj, modules/kv/src/blaze/db/kv/protocols.clj, modules/kv/src/blaze/db/kv_spec.clj, modules/kv/test/blaze/db/kv/mem_test.clj, modules/rocksdb/src/blaze/db/kv/rocksdb.clj, modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
We need this functionality for all key-value instead of only for RocksDB because we will use it in the CQL expression cache.
Needed in: #1051
=> Add Estimated Number of Keys Function

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/scorecard.yml
Set default permissions to read-all and remove write permission for content in push-image and for pages in release.
=> Improve Workflow Permissions

.github/workflows/scorecard.yml
Score card isn't compatible with merge-group event trigger.
=> Remove Merge Group Trigger from Scorecard Workflow

.github/workflows/build.yml
Because PR's are rebased and pushed onto main now, we will have an extra build workflow running for already checked commits. By removing the push trigger, we save that runs.
=> Remove Push Main Event Trigger

.github/scripts/download-resources-query-sort.sh
Timestamps can also contain no milliseconds, so we also have to cut for 'Z' from zulu time.
=> Fix Download Sorted Test

.github/scripts/evaluate-measure-blazectl-stratifier.sh, .github/scripts/evaluate-measure-blazectl.sh
In case blazectl exits with an error, it will be printed now.
=> Improve Error Handling in CI Scripts

modules/interaction/src/blaze/interaction/search/params.clj, modules/interaction/test/blaze/interaction/search/params_test.clj, modules/rest-api/test/blaze/rest_api/capabilities_handler_test.clj, modules/rest-util/src/blaze/handler/fhir/util.clj, modules/rest-util/test/blaze/handler/fhir/util_test.clj, modules/rest-util/test/blaze/handler/util_test.clj
Also make use of multiple _elements parameters.
Closes: #1863
=> Ignore Unknown Values of the _summary Search Param

resources/blaze.edn
For no good reason we had a 26 MiB file size in the resource store. Also some smaller Column Families had a target file size of 3 MiB which is smaller than the write buffer size. I did run an import with 100 k Synthea patients and the performance was over 9000 patients per second.
=> Tidy up the RocksDB File Sizes

modules/rest-api/Makefile, modules/rest-util/Makefile, modules/rest-util/deps.edn
Removed the dependencies crypto-equality/crypto-equality and crypto-random/crypto-random as originally planned. They only sneaked in through a transitive dependency on ring/ring-core from metosin/reitit-ring.
=> Tidy Up Dependencies

modules/cql/src/blaze/elm/code.clj, modules/cql/src/blaze/elm/compiler/external_data.clj, modules/cql/src/blaze/elm/compiler/structured_values.clj, modules/cql/test/blaze/elm/code_spec.clj, modules/cql/test/blaze/elm/compiler/external_data_test.clj, modules/cql/test/blaze/elm/compiler/library_test.clj, modules/cql/test/blaze/elm/compiler/structured_values_test.clj, modules/cql/test/blaze/elm/concept_spec.clj
In case the codes of a Retrieve expression were obtained from a Concept, the source-property expression that get the codes of a Concept was preserved until the clauses had to be calculated. Now the source-property expression will evaluate the codes path on the static Concept during compilation as other expressions also do. After the codes expression is compiled, it's checked for holding a list of codes. So only static codes expressions are supported now explicitly and an appropriate exception is thrown otherwise.
Doing so ensures that the codes argument used in external-data is actually a list of codes and so we also can calculate the query clauses in a simple way.
That allowed to remove the record for the source-property expression. So the codes is simpler and safer as before.
=> Cleanup Codes Evaluation in Retrieve Expression

modules/cql/test/blaze/elm/compiler/structured_values_test.clj
We no longer use the source types. The tests are redundant.
=> Cleanup Structured Value Tests

modules/db-resource-store-cassandra/test/blaze/db/resource_store/cassandra_test.clj, modules/db-resource-store/src/blaze/db/resource_store.clj, modules/db-resource-store/src/blaze/db/resource_store/kv.clj, modules/db-resource-store/test/blaze/db/resource_store/kv_test.clj, modules/db/src/blaze/db/api.clj, modules/db/src/blaze/db/impl/db.clj, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/node/resource_indexer.clj, modules/db/test/blaze/db/api_test.clj, modules/interaction/src/blaze/interaction/delete.clj, modules/interaction/src/blaze/interaction/read.clj, modules/interaction/src/blaze/interaction/transaction.clj, modules/job-async-interaction/src/blaze/job/async_interaction.clj, modules/job-async-interaction/test/blaze/job/async_interaction/util_test.clj, modules/job-re-index/src/blaze/job/re_index.clj, modules/job-scheduler/src/blaze/job_scheduler.clj, modules/job-scheduler/test/blaze/job_scheduler_test.clj, modules/job-scheduler/tests.edn, modules/job-util/src/blaze/job/util.clj, modules/job-util/test/blaze/job/util_test.clj, modules/module-test-util/src/blaze/module/test_util.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/rest-api/src/blaze/rest_api/async_status_cancel_handler.clj, modules/rest-api/src/blaze/rest_api/async_status_handler.clj, modules/rest-util/src/blaze/fhir/response/create.clj, modules/rest-util/src/blaze/handler/fhir/util.clj, modules/rest-util/test/blaze/handler/fhir/util_test.clj
Before this change, the KV Resource Store used it's thread pool for both loading and parsing/conforming the resources. However loading is I/O but parsing/conforming is CPU bound. So it is better to use the KV Resource Store Executor only for the loading, the I/O part.
With this change the KV Resource Store uses do-async to change to a common ForkJoinPool thread. This change has also the advantage that functions that are applied after the returned future do not have to change the thread pool because the futures are already on the common ForkJoinPool.
Removed all pool switching async functions. Tested the thread pool used.
=> Optimize Thread Usage while Loading Resources

docs/implementation/database.md, modules/cql/src/blaze/elm/util.clj, modules/cql/test/blaze/elm/util_spec.clj, modules/cql/test/blaze/elm/util_test.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj
The function now returns a vector of the type name instead of the rendered string List<...> for list types.
=> Refactor Function blaze.elm.util/parse-type

.github/workflows/build.yml
Push image will now depend on fmt, lint, test and test-root.
=> Improve CI Perf by Build Before Testing

modules/cql/test/blaze/elm/compiler/library_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q59-icd10-code-version-independent.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q59-icd10-code-version-independent.json
I was unsure but because the retrieve expression uses FHIR Search internally, it's actually version independent.
=> Demonstrate the Version Independent CQL Retrieve

.clj-kondo/config.edn, .github/workflows/build.yml, modules/rest-api/.clj-kondo/config.edn
Added forgotten blaze.rest-api.batch-handler-test/with-handler to lint-as because handler was considered the handler function at the same namespace and the type checking used that handler function to discover the return value of calling handler instead of the handler function defined by with-handler.
=> Update clj-kondo to v2024.08.01

modules/cql/src/blaze/elm/compiler/date_time_operators.clj, modules/cql/test/blaze/elm/compiler/date_time_operators_test.clj
All the date calculation in CQL depends on local date/time. Now in the evaluation context needs to be an OffsetDateTime in order to deliver the offset but the actual now expression has to return a LocalDateTime relative to the offset from itself.
=> CQL Now Should return a LocalDateTime

modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/middleware/params.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
module: operation-evaluate-measure
* apply parinfer-required formatting
* add failing POST regression test for https://github.com/samply/blaze/issues/512
* major refactoring: tests: separate handler instance tests from handler
type tests (WIP)
* add missing test for "with missing measure parameter" POST requests
* other minor refactorings
=> Make sure we return 422 on non-existing measure POST requests (Fixes #512)

modules/db/src/blaze/db/impl/batch_db.clj, modules/db/src/blaze/db/impl/index/resource_handle.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/impl/index/resource_handle_spec.clj
=> Fix False Positives while Checking Referential Integrity

.github/workflows/build.yml
We can't update to v1.12.x because there are problems with Cloverage:
* https://github.com/cloverage/cloverage/issues/347
* https://github.com/cloverage/cloverage/issues/345
* https://github.com/cloverage/cloverage/issues/102
=> Update Clojure in CI

cljfmt.edn, modules/coll/.clj-kondo/config.edn, modules/coll/src/blaze/coll/core.clj, modules/coll/test/blaze/coll/core_test.clj, modules/cql/.clj-kondo/config.edn, modules/db/src/blaze/db/impl/iterators.clj, modules/db/test/blaze/db/api_test.clj
Before some reducible collections like from the iterators namespace and such created by the with-open-coll macro did not implement Counted. So they could not directly counted and instead had to be converted into a vector first.
Needed by #1382
=> Make more Reducible Collections Counted

modules/db/src/blaze/db/node/tx_indexer/verify.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/node/tx_indexer/verify_test.clj, modules/load-test/Makefile
Like for updates, we don't like to create a new version of an already deleted resource if it is deleted again. Instead we just ignore all subsequent deletes.
=> Don't Create a Version for Double Deletes

modules/db/src/blaze/db/impl/index/resource_as_of.clj, modules/db/src/blaze/db/impl/index/resource_handle.clj, modules/db/src/blaze/db/impl/index/system_as_of.clj, modules/db/src/blaze/db/impl/index/type_as_of.clj, modules/db/test-perf/blaze/db/impl/index/resource_handle_test_perf.clj, modules/db/test/blaze/db/impl/index/resource_handle_spec.clj, modules/db/test/blaze/db/impl/index/resource_handle_test.clj
Before this commit, resource handles had the t at which it was purged as field called purged-at. That field was used later to decide whether a resource handle should be part of a history at a particular t.
After this commit, the resource-handle! function will take an additional argument called base-t and will only return resource handles not purged at this base-t. Doing so, there will be never a purged resource handle and so doesn't need to be checked at all. So the field purged-at is gone.
=> Refactor How Purging Reflects in Resource Handles

modules/db/src/blaze/db/impl/search_param/token.clj, modules/db/test/blaze/db/api_test.clj
=> Fix Returning Resources with Non-Matching Identifier

docs/implementation/fhir-data-model.md, profiling/blaze/profiling.clj
* cljfmt: add `profiling` folder
* format: `docs/implementation/fhir-data-model.md`
=> Misc Fixes

modules/db-tx-log/src/blaze/db/tx_log/spec.clj, modules/db/.clj-kondo/config.edn, modules/db/src/blaze/db/node.clj, modules/db/src/blaze/db/node/tx_indexer/verify.clj, modules/db/test/blaze/db/impl/index/rts_as_of_spec.clj, modules/db/test/blaze/db/node/tx_indexer/expand_spec.clj, modules/db/test/blaze/db/node/tx_indexer/expand_test.clj, modules/db/test/blaze/db/node/tx_indexer/verify/spec.clj, modules/db/test/blaze/db/node/tx_indexer/verify_spec.clj, modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
Especially check that :purged-at is always larger than :t in rts/index-entries.
=> Improve Internal DB Specs

Makefile, modules/db/Makefile
In order to initialize properly, the server needs the Job IG resource files in specific locations (see below).
Since those files are prepped only if they did not exist before, we need do delete them every time we make a `make clean`.
Context:
* the Job IG resource files are generated by `make -C job-ig build`, and saved in the folder `job-ig/fsh-generated/resources`.
* then, when `clojure -X:deps prep` is executed, the resource files are copied to the individual resources
path's (e.g.
`modules/job-re-index/resources/blaze/job/re_index/CodeSystem-ReIndexJobOutput.json`) via `build/copy-profiles`. But this only happens if the folders don't already exist. See
https://clojure.org/reference/deps_edn#prep_lib
If the server cannot find the files in their right locations, it will fail to …
=> Improve Project Cleaning

README.md
The badge change to an orange, which looks like there is a problem with the release. Changed it to a neutral blue like the Docker pull badge.
=> Change Color of Release Badge

modules/cql/src/blaze/elm/compiler/arithmetic_operators.clj, modules/cql/src/blaze/elm/compiler/clinical_operators.clj, modules/cql/src/blaze/elm/compiler/conditional_operators.clj, modules/cql/src/blaze/elm/compiler/date_time_operators.clj, modules/cql/src/blaze/elm/compiler/external_data.clj, modules/cql/src/blaze/elm/compiler/list_operators.clj, modules/cql/src/blaze/elm/compiler/reusing_logic.clj, modules/cql/src/blaze/elm/compiler/string_operators.clj, modules/cql/src/blaze/elm/compiler/type_operators.clj, modules/db/src/blaze/db/api.clj, modules/db/src/blaze/db/api_spec.clj, modules/db/test/blaze/db/api_test.clj, modules/job-async-interaction/src/blaze/job/async_interaction/util.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-patient-everything/src/blaze/operation/patient/everything.clj, modules/page-id-cipher/src/blaze/page_id_cipher.clj, modules/rest-util/src/blaze/handler/fhir/util.clj
The new blaze.db.api/deleted? function makes it more easy to detect whether a resource handle is deleted. Before that we had to test if the :op of the handle equals :deleted.
=> Introduce Resource Handle Deleted Function

modules/rest-util/src/blaze/middleware/fhir/output.clj, modules/rest-util/test/blaze/middleware/fhir/output_test.clj
In case that the generation of XML for responses failed, an OperationOutcome was already produced - but the status code was kept at 200. This was incorrect: in such a case that the server is unable to generate the XML output, the status code should be changed to 500.
=> Fix Response Status Code for Failing XML Emits

modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q10.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q16.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q28-relationship-procedure-condition.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q3.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q45-histology.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q6.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q9.cql
Using equivalent works since #1872 and has the advantage that version and display doesn't influence the equality.
=> Use Equivalent Instead of Contains for Code Comparison

.github/scripts/download-resources-query.sh, docs/api.md, modules/interaction/src/blaze/interaction/search/nav.clj, modules/interaction/src/blaze/interaction/search/params.clj, modules/interaction/src/blaze/interaction/search_type.clj, modules/interaction/test/blaze/interaction/search_type_test.clj
=> Implement Parameter _total in FHIR Search

.github/scripts/install-xq.sh, .github/scripts/read-binary-content-not-found.sh, .github/scripts/read-binary-content-via-json-found.sh, .github/scripts/read-binary-content-via-xml-found.sh, .github/workflows/build.yml, modules/rest-api/src/blaze/rest_api/routes.clj, modules/rest-api/src/blaze/rest_api/spec.clj, modules/rest-util/src/blaze/middleware/fhir/output.clj, modules/rest-util/test/blaze/middleware/fhir/output_test.clj
=> Implement Download of Binary Resources

.github/terminology-tests/parameters-expand.sh, .github/terminology-tests/remove-r5-tests.jq, .github/workflows/build.yml, modules/operation-value-set-expand/src/blaze/fhir/operation/value_set/expand.clj, modules/operation-value-set-expand/test/blaze/fhir/operation/value_set/expand_test.clj, modules/terminology-service/src/blaze/terminology_service/local/code_system/default.clj, modules/terminology-service/src/blaze/terminology_service/local/value_set/expand.clj, modules/terminology-service/src/blaze/terminology_service/spec.clj, modules/terminology-service/test/blaze/terminology_service/local_test.clj
Test cases listed in `.github/terminology-tests/remove-r5-tests.jq` are excluded because they need R5 representations of the ValueSet resource.
Closes: #2290
=> Pass Parameters Expand Terminology Tests

modules/rest-util/src/blaze/middleware/fhir/output.clj, modules/rest-util/test/blaze/middleware/fhir/output_test.clj
We did not serialize the OperationOutcome to JSON at all and did not change the Content-Type header to application/fhir+json.
=> Fix Binary Output in Case of Decoding Errors

modules/db/src/blaze/db/impl/search_param/token.clj, modules/db/src/blaze/db/node.clj, modules/db/test/blaze/db/api_test.clj, modules/db/test/blaze/db/search_param_registry_test.clj
Also ensure that Resources with Group references with ID's identical to Patient ID are not found.
=> Allow more Search Params in Optimization

docs/performance/fhir-search.md, docs/performance/fhir-search/code-date-patient-search.sh, docs/performance/fhir-search/code-patient-search.sh, docs/performance/fhir-search/util.sh
* use 1000 patients instead of 100 for better accuracy
* use patients over a certain age to get a better distribution of patients over the index (before just the first 100 patients were used)
* shuffle the patients
* use patient ID's instead of whole references because that's what people usually use
* use POST instead of GET because of the higher number of patients
=> Improve Performance Tests of Code Patient Search

.github/workflows/build.yml
It uses AgeInYears(), which depends on the time of execution.
=> Remove Time Sensitive CQL Query

modules/db/test/blaze/db/search_param_registry_test.clj, modules/fhir-structure/src/blaze/fhir/spec/impl/xml.clj, modules/fhir-structure/src/blaze/fhir/structure_definition_repo/spec.clj, modules/job-util/test/blaze/job/util_test.clj, modules/operation-totals/test/blaze/fhir/operation/totals_test.clj, modules/rest-api/test/blaze/rest_api/batch_handler_test.clj, modules/rest-api/test/blaze/rest_api/metadata_handler_test.clj, modules/rocksdb/test/blaze/db/kv/rocksdb/impl_test.clj, modules/rocksdb/test/blaze/db/kv/rocksdb_test.clj
The structure definition repo should not be recreated for each test. There is a central instance in blaze.fhir.test-util.
Also use :via instead of :pre for init test with  structure definition repo.
=> Prevent Recreation of Structure Definition Repo

modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q61-encounter-class.cql, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q61-encounter-class.json
This test uses Encounter.class which is a Coding in R4 to test that the equivalent (~) operator works on FHIR Coding and CQL Code. The test also has a version on one of the Encounter classes to test that equivalent ignores the version of a Coding.
=> Add FHIR Coding Equivalent CQL Code CQL Test

docs/deployment/full-standalone.md
The note on Safari was removed, because with the `/etc/hosts` entry, Safari also works.
Closes: #2620
=> Add a Note that /etc/hosts Entry is Required

deps.edn, job-ig/Makefile, modules/admin-api/deps.edn, modules/cql/deps.edn, modules/extern-terminology-service/deps.edn, modules/fhir-structure/build.clj, modules/frontend-e2e/Makefile, modules/frontend-e2e/test-data/Makefile, modules/job-compact/deps.edn, modules/job-scheduler/deps.edn, modules/job-util/deps.edn, modules/kv/Makefile, modules/kv/build.clj, modules/luid/deps.edn, modules/operation-code-system-validate-code/deps.edn, modules/operation-measure-evaluate-measure/deps.edn, modules/operation-value-set-expand/deps.edn, modules/operation-value-set-validate-code/deps.edn, modules/rest-api/deps.edn, modules/server/build.clj, modules/terminology-service/deps.edn
Clojure Deps tries to cache the prom-metrics repo concurrently which will break. The workaround is to put the dependency right into the deps.edn file of affected modules.
=> Fix Caching of prom-metrics Git Repo

.github/workflows/build.yml
Normally in case any deps of pre-push-image fail, the job is skipped and so doesn't fail itself. With `if: always()` and the check script, it will fail on any failing or cancelled dependent job.
=> Fail pre-push-image on Failing Deps

modules/fhir-structure/deps.edn, modules/fhir-structure/src/blaze/fhir/spec/impl.clj
Remove a cache of the rather simple calculation
```clojure
(keyword (str (name key) (su/capital (name type))))
```
I've found nothing in the git history that proves the effectiveness of this cache. Also after #2488 that cache was only used for XML processing which is not as widely used as JSON.
Without this cache, we can remove the caffeine dependency from fhir-structure.
=> Remove Choice Type Cache from Module fhir-structure

modules/byte-buffer/Makefile, modules/byte-string/Makefile, modules/byte-string/deps.edn, modules/byte-string/src/blaze/byte_string.clj, modules/cache-collector/deps.edn, modules/db/test/blaze/db/tx_log/local_test.clj, modules/fhir-test-util/deps.edn, modules/luid/deps.edn, modules/module-base/deps.edn, modules/page-id-cipher/deps.edn, modules/test-util/deps.edn
Removed the dependencies:
* com.google.errorprone/error_prone_annotations
* com.google.guava/failureaccess
* com.google.guava/listenablefuture
* org.jspecify/jspecify
I could remove the object-mapper-module from byte-string because we no longer serialize byte strings as CBOR. We serialize our own Hash class instead.
=> Remove Dependencies

modules/fhir-structure/src/blaze/fhir/spec/resource.clj, modules/fhir-structure/test/blaze/fhir/spec/generators.clj, modules/fhir-structure/test/blaze/fhir/spec_test.clj
The problem was that the property `policyRule` comes after the property `policy` in the list of element definitions. Both have the same prefix and `policy` is a BackboneElement. The function
separate-element-definitions* used string prefix on path as termination condition, so `policyRule` was counted as member of `policy`. I just added a `.` to make the prefix check robust.
Closes: #2700
=> Fix Consent Resource policyRule Property

modules/frontend/Dockerfile
Docker scout complains about an unapproved base image tag. Only the newest version 24 and the LTS version 22 are listed as supported tags under: https://hub.docker.com/_/node
=> Revert to Node 22 LTS

.github/workflows/build.yml, modules/db/Makefile, modules/db/test/blaze/db/api_test.clj
Separate slow DB tests so that they can run in parallel to the other DB tests.
=> Separate Slow DB Tests

modules/interaction/src/blaze/interaction/transaction.clj, modules/interaction/src/blaze/interaction/util.clj, modules/module-base/src/blaze/module.clj, modules/module-base/src/blaze/module_spec.clj, modules/module-base/test/blaze/module_test.clj, modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj, modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_spec.clj, modules/rest-api/src/blaze/rest_api/structure_definitions.clj, modules/rest-api/test/blaze/rest_api/structure_definitions_test.clj, modules/terminology-service/src/blaze/terminology_service/local/code_system/util.clj
It's used in interaction, operation-measure-evaluate-measure, rest-api and terminology-service.
=> Move luid-generator into module-base

docs/tuning-guide.md
The recommended values originated from my performance tests were Blaze will do only one task. Usually it's a good idea to keep more Java heap memory free for more clients and more than one task to do.
=> Cut the Recommended Resource Cache Values in Half

DEVELOPMENT.md, Makefile, job-ig/Makefile, job-ig/package-lock.json, modules/anomaly/README.md
Using `npm install fsh-sushi` caused to install the newest version of SUSHI on any build. Just using `npm install` doesn't do that.
Also updated dependencies and improved DEVELOPMENT.md.
=> Prevent Job-IG to Install New Version of SUSHI

.github/scripts/patient-ids.sh, .github/workflows/build.yml
The script `.github/scripts/patient-ids.sh` did only select at most 50 patients because of default max page size of 50. However it was used to determine the IDs of 100 patients.
=> Fix Multiple Patient FHIR Search Integration Test

.github/scripts/download-resources-query-sort.sh, .github/scripts/download-resources-query.sh
Using a random page size further ensures that paging delivers the same results even with varying page sizes. The random page size is only used at the GET version of the download command, leaving the POST version with the default page size as reference.
=> Use a Random Page Size for Download Tests

modules/admin-api/test/blaze/admin_api_test.clj, modules/fhir-test-util/src/blaze/fhir/test_util.clj, modules/interaction/src/blaze/interaction/history/instance.clj, modules/interaction/src/blaze/interaction/history/system.clj, modules/interaction/src/blaze/interaction/history/type.clj, modules/interaction/src/blaze/interaction/history/util.clj, modules/interaction/src/blaze/interaction/search_compartment.clj, modules/interaction/src/blaze/interaction/search_system.clj, modules/interaction/src/blaze/interaction/search_type.clj, modules/interaction/test/blaze/interaction/history/instance_test.clj, modules/interaction/test/blaze/interaction/history/system_test.clj, modules/interaction/test/blaze/interaction/history/type_test.clj, modules/interaction/test/blaze/interaction/history/util_spec.clj, modules/interaction/test/blaze/interaction/history/util_test.clj, modules/interaction/test/blaze/interaction/search_compartment_test.clj, modules/interaction/test/blaze/interaction/search_system_test.clj, modules/interaction/test/blaze/interaction/search_type_test.clj, modules/interaction/test/blaze/interaction/transaction_test.clj, modules/operation-patient-everything/src/blaze/operation/patient/everything.clj, modules/operation-patient-everything/test/blaze/operation/patient/everything_test.clj, modules/rest-util/src/blaze/interaction/search/util.clj, modules/rest-util/src/blaze/interaction/search/util/spec.clj, modules/rest-util/test/blaze/interaction/search/util_test.clj, modules/spec/src/blaze/spec.clj, profiling/blaze/profiling.clj, resources/blaze.edn, src/blaze/system.clj, test/blaze/system_test.clj
The function will create bundle links depending of the FHIR version in use. This is the first function doing so. The function is build as component which takes the FHIR version at initialization and returns an appropriate function. Although the implementation for FHIR v6.0.0-ballot3 is already given, and could be even used by setting the env var `FHIR_VERSION` accordingly, this is not supported until full R6 availability is documented.
=> Extract Bundle Link Creation into a Function

modules/module-base/deps.edn, modules/module-test-util/deps.edn, src/blaze/system.clj
We have to remove the use of `prep` which we actually never used anyway. So the migration is simpler as expected. In #3022 we can explore the use of the new Integrant features.
Closes: #2704
=> Migrate Integrant to v1.0
